### ISSUE TITLE
django-configurations support

### ISSUE THREAD

**Issue by philippeluickx** [theskumar/python-dotenv#1]
Hei,

Seems like the support in django-configurations for dotenv seems to be in the master.
Update the README?

Thanks for a great lib!

**Comment by theskumar** [comment]
It's added now https://github.com/theskumar/python-dotenv/commit/e2c7c6fb781cc483e3ee32585fe1b79de5e4d428#diff-04c6e90faac2675aa89e2176d2eec7d8R69. Will wait for 0.9.0 for acknowledge it more prominently.

**Comment by philippeluickx** [comment]
Thanks!

**Comment by theskumar** [comment]
This has been added to `Related Projects` section. Closing this issue now.
