### ISSUE TITLE
Variable not found ("None" returned) on a Mac

### ISSUE THREAD

**Issue by shirki** [theskumar/python-dotenv#104]
Hi, we are using dotenv for a project and are getting strange behavior. 

While the environment variable is working just fine on a Windows machine, it is not able to read at all on a Mac. It returns "None" even though the variable is clearly there. There seem to be no other issues.

In X.py file:
```
from dotenv import load_dotenv
load_dotenv()
import os
HOME_PATH = os.getenv("SQUABBLE_HOME_PATH")
```
In .env file:
```
SQUABBLE_HOME_PATH = '/path/to/squabble_runner/'
```

While running:
```
Traceback (most recent call last):
  File "XXXX/X.py", line 27, in controversy_score
    input_file_path = HOME_PATH + 'lib/squabble_input.txt'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

This is on Sierra, Python 3.6.2.

As mentioned above, the same code runs just fine on a PC.
Any help would be appreciated!

**Comment by TDiazT** [comment]
Same as well

**Comment by shirki** [comment]
@theskumar Several people seem to be having this issue - would really appreciate your help on this one! Thanks in advance.

**Comment by theskumar** [comment]
@shirki can you try providing absolute path to .env file or use `find_dotenv()` in the call to `load_dotenv()` see if you are still facing issue?

**Comment by theskumar** [comment]
I've tried running your example on Mac, it works with:

python-dotenv==0.8.2
Python 3.6.4

**Comment by garyking** [comment]
I have the same problem as others here. If I use `load_dotenv()` then it doesn't work. If I use `load_dotenv(find_dotenv())` then it works fine though.

**Comment by shirki** [comment]
@theskumar Neither load_dotenv(find_dotenv()) nor providing an absolute path worked.

python-dotenv: 0.8.2
Python: 3.6.2
Mac: Sierra

**Comment by theskumar** [comment]
@shirki sorry for the issues you are facing. But I don't seem to able to reproduce the issue. One last time, I would just advice you to use the absolute path to the .env file. It could be file permission issue, but I can't say for sure.

**Comment by TDiazT** [comment]
I tried running `load_dotenv(verbose=True)` and I get:
```python
 UserWarning: File doesn't exist 
  warnings.warn("File doesn't exist {}".format(self.dotenv_path))
```

I tried the other example in the doc:
```python
from pathlib import Path  # python3 only
env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)
```
which results in
```python
TypeError: argument should be string, bytes or integer, not PosixPath
```
I `str(env_path)` to which I still get that the `.env` file doesn't exist.

I also tried:
```python
from dotenv import load_dotenv
import os
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
env_path = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path=env_path, verbose=True)
```
but still the same error.

**Comment by TDiazT** [comment]
Daaaaamn.... I just realised my file was named `.env.py` !! 😐 

Just renamed it to `.env` and it worked... of course

**Comment by theskumar** [comment]
It happens no worries.

**Comment by shirki** [comment]
@theskumar Can you please reopen the issue? I tested it again with python 3.6.5, as well as with an absolute filename or with the load function, and the issue persists. As opposed to @TDiazT, my file name is definitely .env 😄. 

@devrsw, are you still getting the same error?

 Thanks!

**Comment by joarleymoraes** [comment]
It happened to me as on Docker/Ubuntu14.04. I had to explicitly load with `dotenv_path`:

```
from dotenv import load_dotenv
load_dotenv(dotenv_path='.env', verbose=True)

```

**Comment by ccennis** [comment]
i'm on a mac, high sierra and I had the same issue until I changed it to: 

```
from dotenv import load_dotenv
from dotenv import find_dotenv
load_dotenv(find_dotenv())
```

**Comment by yashg5** [comment]
This solved my issue:
from dotenv import load_dotenv
from dotenv import find_dotenv
load_dotenv(dotenv_path=find_dotenv(), verbose=True)

**Comment by kashaziz** [comment]
I had similar issue on Python 3.5 (working fine on later versions). What worked for me is using explicit path to .env. Assuming the env file is in _projects_ folder, it can be loaded as follows:

`load_dotenv(os.path.join(BASE_DIR, "backend", ".env"))`

**Comment by andhint** [comment]
I had similar issues where adding the path or find_dotenv() didn't work. I recreated my .env file to be sure it had the right extension and that fixed it. I'm guessing I messed something up creating the .env the first time somehow.

**Comment by KaeganCasey** [comment]
Saw this issue and wanted to post what worked for me since none of the above fixes were working for my problem.

I had trouble getting python-dotenv to work because I had jupyterlab installed in my conda (miniforge) base environment and had installed python-dotenv in a separate environment. python-dotenv wasn't recognizing the .env file correctly from jupyterlab and after a lot of trouble shooting all I had to do was install python-dotenv in my base conda env as well. Then load_dotenv() correctly recognized my .env file in the same folder as my notebook.
 
Just wanted to post in case someone else had the same problem.
