### ISSUE TITLE
`dotenv set` cannot accept values that start with `-`

### ISSUE THREAD

**Issue by skeledrew** [theskumar/python-dotenv#107]
I didn't see a resolution for #87 and it's closed, so I'm opening as a new issue again.

Trying something like `dotenv set NEG_NUM -100` returns "Error: no such option: -1" instead of setting. Quoting doesn't help. Is there a way around this or am I stuck editing the file manually?

**Comment by earlgreyness** [comment]
@skeledrew There is a way around this: `dotenv set NEG_NUM "'-100'"`.

**Comment by bbc2** [comment]
Hello! You can also try:

```bash
dotenv set -- NEG_NUM -100
```

Many command-line parsers understand that arguments after `--` are not options.  This is not specific to python-dotenv so this issue should probably be closed now.

**Comment by earlgreyness** [comment]
> Hello! You can also try:
> 
> ```shell
> dotenv set -- NEG_NUM -100
> ```
> 
> Many command-line parsers understand that arguments after `--` are not options. This is not specific to python-dotenv so this issue should probably be closed now.

@bbc2 You are right. Command line interface for dotenv (including arguments parsing) is [handled](https://github.com/theskumar/python-dotenv/blob/v0.9.1/dotenv/cli.py#L5) by click library. Here is even the relevant error message in the [click source code](https://github.com/pallets/click/blob/7.x/click/exceptions.py#L166).
