### ISSUE TITLE
load_dotenv() misbehaves with no parameters

### ISSUE THREAD

**Issue by EmilyRagan** [theskumar/python-dotenv#111]
I do not have a settings.py file, so I am calling dotenv from my main.py, but it is still in the same folder as my .env file. Calling `load_dotenv()` without any parameters does not access the .env correctly, as every time that I try to use `os.getenv` to get an environment variable, it says "None". When I call `load_dotenv(ENV_PATH)` with `ENV_PATH = Path(".") / ".env"`, it works.

**Comment by cjauvin** [comment]
I believe this is the same issue as https://github.com/theskumar/python-dotenv/issues/108, for which I have submitted this PR https://github.com/theskumar/python-dotenv/pull/109, which has received no attention so far.

**Comment by sloria** [comment]
This is fixed in the latest version (0.9.1 as of this writing). @theskumar This issue can be closed.

**Comment by basharSaid** [comment]
The issue of loading seems to be fixed in 0.9.1 (as `load_dotenv()` now reads values from a `.env` file in a directory level _above_), but the [".env not found" warning](https://github.com/theskumar/python-dotenv/blob/master/dotenv/main.py#L65) is buggy with `load_dotenv(verbose=True)`:

```python
UserWarning: File doesn't exist 
  warnings.warn("File doesn't exist {}".format(self.dotenv_path))
```
Note the empty value in the warning message above! (line 1)

The value `self.dotenv_path` is empty by default, hence doesn't display. That should probably print the name of the file that was tried to be read.

**Comment by bbc2** [comment]
The issue was indeed fixed so I'm going to close it.

> The value `self.dotenv_path` is empty by default, hence doesn't display. That should probably print the name of the file that was tried to be read.

You're right in that it's not a great message, but it wouldn't make sense to show just one path since several could have been tried (that's what `find_dotenv` does).  Displaying something like `No .env found` instead would probably make sense.

**Comment by cocodrino** [comment]
I'm having similar problem, when I was deploying my flask app using a Procfile it was working perfectly, now I'm using a Dockerfile and I'm getting this error

```bash
2019-09-18T17:23:10.768993025Z app[web.1]:  * Restarting with stat
2019-09-18T17:23:11.014721433Z app[web.1]: /usr/local/lib/python3.7/site-packages/dotenv/main.py:52: UserWarning: File doesn't exist 
2019-09-18T17:23:11.014754178Z app[web.1]:   warnings.warn("File doesn't exist {}".format(self.dotenv_path))  # type: ignore
2019-09-18T17:23:11.014759728Z app[web.1]:  * Debugger is active!

```
