### ISSUE TITLE
.env file having '\' does not work properly

### ISSUE THREAD

**Issue by dhruvinsh** [theskumar/python-dotenv#112]
.env file with variable containing backward slash '\' does not load properly,
For example, .env file with
`test=hi\hello`

and in python,

```
>>> from dotenv import load_dotenv
>>> load_dotenv()
True
>>> import os
>>> print os.getenv('test')
hi\\hello
>>> print repr(os.getenv('test'))
u'hi\\\\hello'
```
python-dotenv: 0.8.1
windows: 10
python: 2.7.14

**Comment by anthonyjmartinez** [comment]
Wrap the env var in double quotes and it will pass correctly.
