### ISSUE TITLE
Release latest version to PyPi

### ISSUE THREAD

**Issue by asfaltboy** [theskumar/python-dotenv#122]
I'm most excited about the "run arbitrary command" feature and the other changes (https://github.com/theskumar/python-dotenv/compare/v0.8.2...master) seem harmless, can we help to move forward a new version release to PyPi ?

**Comment by asfaltboy** [comment]
@theskumar ping

**Comment by theskumar** [comment]
Tada 🎉 0.9.0 is up! 

![image](https://user-images.githubusercontent.com/236356/43465764-a4cd838a-94fb-11e8-9f00-094e01515c24.png)

Thanks everyone for all the help!
