### ISSUE TITLE
PR #109 breaks code that needs env file in the install directory

### ISSUE THREAD

**Issue by trentgerman** [theskumar/python-dotenv#124]
Hi all -

The newest version of dotenv has broken some of our code. At our shop we would install code in a virtual environment, in 

 /home/user/venv/lib/python2.7/site-packages/myrepo

and then place the .env file in

/home/user/venv/lib/python2.7/site-packages/myrepo/.env

using python-dotenv==0.8.0 fixes the issue, but I would like to find a better way forward. 

I have tried running find_dotenv(usecwd=True)  

and

find_dotenv(usecwd=False ) 

And this does not appear to fix the issue.

Is there a recommended setting that will fix this? If not I am happy to add a test to illustrate whats going on here.

**Comment by theskumar** [comment]
Hi @trentgerman , i'm sorry you are facing issues. Let's try to go with tests first and then we'll see that to do next.

For now, I would suggest putting explicit path to .env if possible, that how thing were planned in the beginning of project.

> Explicit is better than implicit – Zen of Python.

**Comment by theskumar** [comment]
@trentgerman please try with the latest release (>0.9.1) & let us know if you are still facing the issue. Re-open this issue if needed.

**Comment by trentgerman** [comment]
Hey! Thanks for getting back to me, the newest version did not appear to fix the issue. I'll see if I can write a unit test that reproduces the problem over the weekend.
