### ISSUE TITLE
conda-forge release

### ISSUE THREAD

**Issue by jamesmyatt** [theskumar/python-dotenv#126]
Can you add deploying the conda-forge release to the CI pipeline, please? I'm not sure who maintains that repo.

https://github.com/conda-forge/python-dotenv-feedstock

**Comment by theskumar** [comment]
It seems that they already have some kind of bot to make PR and update the releases when a new release is available here. I'm not sure if I can do anything to help in the whole process.

**Comment by jamesmyatt** [comment]
I assume it's @proinsias

**Comment by theskumar** [comment]
Hi @jamesmyatt , I am not very clear here what is expected here. I'm closing this. Please reopen if you feel something we help with.
