### ISSUE TITLE
flatten_and_write writes windows newlines

### ISSUE THREAD

**Issue by tino** [theskumar/python-dotenv#13]
And that is a problem on my unix systems... 

https://github.com/theskumar/python-dotenv/blob/master/dotenv.py#L96

And so are the `"` around the value. I don't think these are necessary.

Is it possible to change this?

**Comment by theskumar** [comment]
Thanks for reporting this. Yes, the line endings should be fixed to be os independent. I'll switch to `\n` and let os.write handle it. 

For `"`, I will keep it as it for now. As we have plans for supporting `$` as proxy value and things like `export X="ads s"[1]. I need to give a second thought before changing it, but would definitely would be in my list. I'm creating a ticket for it, so it can be tracked.

[1] https://github.com/bkeepers/dotenv#usage
