### ISSUE TITLE
Variable expansion for 'directory .env is in'

### ISSUE THREAD

**Issue by altendky** [theskumar/python-dotenv#133]
https://github.com/altendky/st/blob/de71e071b46bb9863a9bcf94598d7048277f617f/.env#L1
```bash
PYQTDESIGNERPATH=${PYQTDESIGNERPATH};sub/epyqlib/epyqlib;sub/epyqlib/epyqlib/widgets
```

It would be helpful to have a variable that represents the directory that the `.env` file being loaded is located in.  The paths such as `sub/epyqlib/epyqlib` are relative to the `.env`-containing directory but it would be helpful if they could be absolute rather than working-directory dependent.

I imagine something like below though perhaps something that avoids any chance of blocking access to a regular environment variable someone might define.

```bash
PYQTDESIGNERPATH=${PYQTDESIGNERPATH};${ENV_DIR}/sub/epyqlib/epyqlib;${ENV_DIR}/sub/epyqlib/epyqlib/widgets
```

If you like the idea I might be able to come up with a PR.

**Comment by altendky** [comment]
For the record, here's my workaround for now.

https://github.com/altendky/pyqt5-tools/blob/6270fe38245bee5f495a05d3f8afa802f849be6b/src/pyqt5_tools/entrypoints.py#L70
```python3
env_path = dotenv.find_dotenv()
os.environ['DOT_ENV_DIRECTORY'] = str(pathlib.Path(env_path).parent)
dotenv.load_dotenv(dotenv_path=env_path)
```

**Comment by theskumar** [comment]
This logic is too much like a magic! I'm sorry to decline this feature request.
