### ISSUE TITLE
Stdout/stderr output isn't flushed out by `dotenv run`

### ISSUE THREAD

**Issue by asfaltboy** [theskumar/python-dotenv#137]
For example, running django web server normally sends continuous output to stdout/stderr; however, via python-dotenv it doesn't show the server output. This may have something to do with the fact that python-dotenv is [using `subprocess.Popen` and then `p.communicate()`][2] (which collects all the output when the process returns).

Here's a quick reproducing script, and output:

```python
import logging
import sys
import time

logging.basicConfig()  # set default stderr handler
log = logging.getLogger()
stdout_handler = logging.StreamHandler(sys.stdout)
log.addHandler(stdout_handler)
print('Starting running with handlers', log.handlers)

while True:
    log.error('Test log')
    time.sleep(1)
```

and the output:

```bash
$ python test.py
Starting running with handlers [<StreamHandler <stderr> (NOTSET)>, <StreamHandler <stdout> (NOTSET)>]
ERROR:root:Test log
Test log
ERROR:root:Test log
Test log
^CTraceback (most recent call last):
  File "test.py", line 13, in <module>
    time.sleep(1)
KeyboardInterrupt

$ dotenv run python test.py
^C
Aborted!
```

As a reference / possible solution, we can look at [python-dotenv-run code][1] which uses either `        ctx.exit(subprocess.call([command] + list(args), shell=True))` on windows or `os.execlp(command, command, *args)` otherwise.

p.s: I'll be happy to submit a PR if one of the solutions above is acceptable.

[1]: https://github.com/uranusjr/python-dotenv-run/blob/master/dotenv_run.py#L35-L40
[2]: https://github.com/theskumar/python-dotenv/blob/master/dotenv/main.py#L286-L301

**Comment by theskumar** [comment]
@venthur - let me know if you have any thoughts on this? 

I'm not too sure, what are the fundamental differences are, I'm not particular interested in changing the current code, unless I understand it fully or until someone else able to explain it better.
