### ISSUE TITLE
CLI doesn't support interactive tty

### ISSUE THREAD

**Issue by thalesmello** [theskumar/python-dotenv#138]
Steps to reproduce:

1. Install cli `pip install python-dotenv[cli]`
2. Create `.env` file containing `FOO=bar`
3. Execute `dotenv run python`

The script currently prints a blank line.

I expect it to load the Python REPL with the environment variables loaded.

**Comment by theskumar** [comment]
I'm happy to merge a working PR for this. I don't have much expertise into tty handling.

**Comment by theskumar** [comment]
The latest version of dotenv should fix it. Please reopen, if it doesn't for you.

Cheers!
