### ISSUE TITLE
set_key() doesn't update the .env file correctly

### ISSUE THREAD

**Issue by dany2691** [theskumar/python-dotenv#140]
Ubuntu 18.04 is my OS and I'm using python 3.6.

I have the next **.env** file:

```
ACTIVATED=True
HOUR=3
MINUTE=7
```
When I call the set_key() function and try to update the value of HOUR, the file is incorrectly updated:

```py
set_key('.env', 'HOUR', '5', '')
```

```
ACTIVATED=True
HOUR=5MINUTE=7
```
The weirdest thing is when I downloaded **python-dotenv** from the github repo everything worked well.

```
ACTIVATED=True
HOUR=5
MINUTE=7
```
Can anybody help me?

**Comment by theskumar** [comment]
You are facing probably because you code missed this update https://github.com/theskumar/python-dotenv/commit/ea0604d60917e15febbd92f259001e6d9012e38b. The latest from master should work for you.
