### ISSUE TITLE
Regression 0.9.1 -> 0.10.0: .env parsed incorrectly

### ISSUE THREAD

**Issue by asyncee** [theskumar/python-dotenv#157]
Hello!

I have upgraded dotenv from 0.9.1 to 0.10 and now my config file is parsed incorrectly.

Example file:

```
$ cat .env
VAR_A=

VAR_B=123
```

Current behaviour on 0.10:
```
$ dotenv list

VAR_A=VAR_B=123
```

Previous (correct) behaviour on 0.9:

```
$ dotenv list

VAR_A=
VAR_B=123
```

**Comment by theskumar** [comment]
@asyncee thanks for reporting this, I'm looking into it.

**Comment by theskumar** [comment]
This is most like due to new regex used, which support multiline values. As an immediate fix you can use empty values within in quotes and that seem to work. 

e.g. 
```
$ cat .env
VAR_A=''

VAR_B=123
```
```
$ dotenv list

VAR_A=
VAR_B=123
```

cc: @bbc2 thoughts?

**Comment by asyncee** [comment]
Thanks! I think that this should be noted in the readme and breaking change should be added to changelog :)

**Comment by bbc2** [comment]
Hello, this is definitely a regression.  I've submitted a fix and added a test case for empty variables.  Let us know if that works for you.

**Comment by asyncee** [comment]
@bbc2 @theskumar i can confirm that fix is working.

You guys are great. Thanks!

**Comment by theskumar** [comment]
v0.10.1 is up. 🎉 

Thanks @bbc2 and @asyncee!
