### ISSUE TITLE
Feature proposal: Encrypted dotenv files

### ISSUE THREAD

**Issue by sebaacuna** [theskumar/python-dotenv#163]
Hi, I have a need for being able to use symmetrically encrypted env files.

Would support for such a feature be welcome in this project? I'm considering whether to fork and extend the functionality or create a separate package that uses `python-dotenv`.

If I were to fork, it would be something like adding a `key` and `key_path` parameter to `load_dotenv` like so:
```python3

load_dotenv(key='ob...Z8=')
load_dotenv(key_path=Path('to/keyfile'))
```

And some additions to the CLI such as:
```sh
dotenv --key-path=encryption.key python ....
```

If there's interest I can write up a spec to review and agree on first, but I'd rather not waste anyone's time if the feeling is that this would be out of scope.

Thanks,
Sebastián

**Comment by Immortalin** [comment]
Rails secrets for python and django?

**Comment by bbc2** [comment]
Interesting use case but probably out of scope for this project.  If you want to encrypt your .env file and load that, I would suggest decrypting it first and then passing the result to `load_dotenv`:

```python
encrypted_env = open(".env").read()
env = decrypt(encrypted_env)
load_dotenv(stream=StringIO(env))
```

**Comment by westurner** [comment]
- https://github.com/bhags1981/python-encrypted-dotenv/blob/master/src/enc_dotenv/main.py#L1-L23
  - pyaescrypt
- openssl
  - From SO: https://stackoverflow.com/questions/16056135/how-to-use-openssl-to-encrypt-decrypt-files/61166202#61166202 :
> To encrypt a file:
> 
> `openssl aes-256-cbc -e -salt -pbkdf2 -iter 10000 -in plaintextfilename -out encryptedfilename`
> 
> To decrypt a file:
> 
> `openssl aes-256-cbc -d -salt -pbkdf2 -iter 10000 -in encryptedfilename -out plaintextfilename`

... You can (and should) change that `10000` (the number of rounds) to a higher, different number (which must be the same for encrypt and decrypt calls).

- GPG
  - symmetric
  - assymetric
    - for CI builds, the runner does not need to have the encryption key: only the private key of a recipient
- gpg

**Comment by bbc2** [comment]
Interesting examples, thanks. I'll close the issue since there's no action to take in python-dotenv.

**Comment by rrwen** [comment]
I was looking for something like this, but since it is out of scope and not too difficult to implement with the help of `load_dotenv` as mentioned above, I made a small package for loading/saving encrypted .env files here:

https://pypi.org/project/python-edotenv/

It does not go beyond loading/saving and relies on `python-dotenv` for the most part, but hope it helps someone looking for a similar solution
