### ISSUE TITLE
Add tests to source tarball

### ISSUE THREAD

**Issue by jayvdb** [theskumar/python-dotenv#169]
Please add the tests to the source tarball, so they can be used by rpm to validate the package.

**Comment by dvzrv** [comment]
I 2nd this, as it is a valuable thing to have, when building system packages (e.g Arch Linux here).

**Comment by dvzrv** [comment]
Pypi source tarball that is, as in the github sources it is included.

**Comment by jayvdb** [comment]
Ah, this was fixed in https://github.com/theskumar/python-dotenv/pull/154 , and should be part of the next sdist.
