### ISSUE TITLE
load_dotenv () does not read all the parameters for the .env

### ISSUE THREAD

**Issue by xarpy** [theskumar/python-dotenv#171]
I'm using **lib Path** in my project to set a specific .env location. However when I try to run the python command `runserver` for testing, it returns the error below:

`django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.`

My configuration(_using the suggestion of page on github_) :
```
from dotenv import load_dotenv
env_path = Path('/home/user/configs') / '.env'
load_dotenv(dotenv_path=str(env_path))
```
How can I resolve this problem from the specific path?

**Note**: I am using python 3.4.5 in the project, but using the **lib Path** without the conversion to string, displays the error below:

`TypeError: argument should be string, bytes or integer, not PosixPath`

I believe there must be an error in the function that reads the specific path!

**Comment by josuablejeru** [comment]
Hi, did you still facing this problem?

**Comment by xarpy** [comment]
I found the solution to my problem, just needed to put the full path.
`from dotenv import load_dotenv
env_path = Path('/home/user/configs')
load_dotenv(env_path)`

**Comment by xarpy** [comment]
I found out the solution to my problem, just needed to put the full path

```from dotenv import load_dotenv
env_path = Path('/home/user/configs/.env') 
load_dotenv(env_path)
