### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv' when using PyCharm

### ISSUE THREAD

**Issue by rajkumartreads** [theskumar/python-dotenv#185]
I followed the installation guide at https://github.com/theskumar/python-dotenv#getting-started. I can run the Django project from terminal but could not do it from PyCharm.

I get the following error:
```
Traceback (most recent call last):
  File "G:/Project/abc/manage.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

**Python/Package version used**
Python 3.7 
Django 2.2.1 
python-dotenv 0.10.3

**IDE/OS used**
Using PyCharm on Windows 10 64 bit

**Comment by bbc2** [comment]
Hello, this doesn't look like a Python-dotenv issue.   I would guess that your PyCharm installation isn't using the right virtualenv (the one that has the `dotenv` module).

**Comment by rajkumartreads** [comment]
Hi, I have never used `dotenv` module till date and PyCharm is using the right virtualenv with `python-dotenv`.

I restarted my PC, created a new django project using PyCharm with a new virtualenv. It worked. I'm closing this issue as it is solved but I could not understand the root cause for the error.
