### ISSUE TITLE
Allow updating one DotEnv instance with another

### ISSUE THREAD

**Issue by twosigmajab** [theskumar/python-dotenv#186]
Would you accept a PR that added an `update(self, *others, override=True)` method to the `DotEnv` class, enabling the following?
```python
# setup:
>>> d1 = DotEnv('d1.env')
>>> d1.dict()
{'a': '1', 'b': '1'}
>>> d2 = DotEnv('d2.env')
>>> d2.dict()
{'b': '2', 'c': '2'}
>>> d3 = DotEnv('d3.env')
>>> d3.dict()
{'c': '3'}

# Now we can update d1 with items from d2 and d3:
>>> d1.update(d2, d3)
>>> d1.dict()
{'a': '1', 'b': '2', 'c': '3'}
```

**Comment by bbc2** [comment]
I think I understand the example but I don't see how this is useful.  Could you show a use case for this feature?

**Comment by twosigmajab** [comment]
I maintain a CLI that supports passing multiple `-e/--dotenv` flags.

Suppose `base.env` sets `FOO=1` and `overrides.env` sets `FOO=2`.

An invocation like `<mycli> -e base.env -e overrides.env <subcommand>` should combine base.env and with overrides.env such that FOO=2 by the time the subcommand is run. However, an invocation like `env FOO=3 <mycli> -e base.env -e overrides.env <subcommand>` should result in FOO=3 by the time the subcommand is run.

I have this working already, but if the `DotEnv` class supported merging instances together with override=True, *before* a final call to `set_as_environment_variables()` (with `override=False`), I think it would have been easier.

**Comment by dmig-alarstudios** [comment]
Upvoting this.

My case:
I'm keeping `global.env` in the project root in the repository, each developer (and production environment) can override it with `.env`, which is gitignored.
I expect to have a simple way to override values from `global.env` *retaining variable substitution*.
Right now I use this snippet:
```python
    from dotenv import dotenv_values, find_dotenv

    config = dotenv_values()
    global_config = dotenv_values(find_dotenv('global.env'))

    for k, v in global_config.items():
        config.setdefault(k, v)
```

But it lacks variable substitution. E.g.:
```
# global.env
PGUSER=postgres
PGPASSWORD=postgres
PGHOST=localhost
PGPORT=6543
PGDATABASE=mydb

DSN=postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}
```
this won't work
```
# .env
PGPORT=5432
PGDATABASE=mylocaldb
```

**Comment by bbc2** [comment]
@twosigmajab I think you might be able to solve your problem with `dotenv_values`.  I've recently added an example to the readme which looks a bit like what you're trying to do: https://github.com/theskumar/python-dotenv#load-configuration-without-altering-the-environment.

@dmig-alarstudios To get variable substitution to still work, what about the following:

```python
import os

from dotenv import load_dotenv

load_dotenv(".env")
load_dotenv("global.env")

print(os.getenv("DSN"))
```

It's a bit tricky to understand but, to be fair, python-dotenv isn't really meant as a configuration system. It's mostly here to help developers work with applications taking simple configuration from the environment.  In your case, I would probably not rely on interpolation and let the user override the whole `DSN` in their local .env.
