### ISSUE TITLE
Could not find version that satisifes the requirement python-dotenv 

### ISSUE THREAD

**Issue by chrismp** [theskumar/python-dotenv#19]
I'm using Python 3.5 on a 32-bit Win7 machine.

When I run `pip install python-dotenv` or  `pip install -U python-dotenv`, I get this error:

`Could not find version that satisifes the requirement python-dotenv `

**Comment by theskumar** [comment]
@chrismp sorry but I don't have a windows machine handy to test this issue.

Are you able to confirm that this command runs on your machine:

```
pip install https://github.com/theskumar/python-dotenv/archive/master.zip
```

Thanks.

**Comment by theskumar** [comment]
@chrismp please re-open if needed.
