### ISSUE TITLE
ImportError: No module named typing

### ISSUE THREAD

**Issue by gudata** [theskumar/python-dotenv#195]
With
```
Python 2.7.15 :: Anaconda, Inc.

```
when I run the install instructions I get
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from dotenv import load_dotenv
  File "/home/guda/anaconda3/envs/essential/lib/python2.7/site-packages/dotenv/__init__.py", line 1, in <module>
    from typing import Any, Optional  # noqa
ImportError: No module named typing
```

Is this typing module only  for python3 and does this module support python2?

**Comment by bbc2** [comment]
Your error is surprising because `typing` is a dependency of `python-dotenv` for Python < 3.5 and it is available for Python 2.  It should have been installed along with `python-dotenv`, but I don't really know how Anaconda works.  Is it present in your virtualenv, in `site-packages`?

**Comment by gudata** [comment]
When I installed manually the typing module it works.
I do the install with 
```
conda install ...
```
Also wondering why the dependency wasn't installed automatically.

Thanks!
