### ISSUE TITLE
Unexpected Behavior when Parsing Duplicate Key

### ISSUE THREAD

**Issue by wg40** [theskumar/python-dotenv#197]
Hello. I started using this package yesterday and I am sorry if I am missing something simple.
I am trying to read an env file that looks like this:
```
export hello=hi
export greetings=${hello}
export goodbye=bye
export greetings=${goodbye}
```
 To read it, I wrote the following small program:
```python
import os
import dotenv
from pathlib import Path

env_path = './test.env'
dotenv.load_dotenv(dotenv_path=env_path,verbose=True)
print(os.getenv('greetings'))
```
When I run this program, it outputs a single empty line. This happens even when I set override to True. I was expecting the program to output 'bye'. Is this a bug or the expected behavior for handling duplicate keys ? I am currently running 3.7.3 and python-dotenv version 0.10.3. Thank you.

**Comment by wg40** [comment]
Quick update. I just tried the program again with the following env file:
```
export hello=hi
export goodbye=bye
export greetings=${hello}
export greetings=${goodbye}
```
This time, my program output 'bye'. 

I am not sure why changing the order allowed greetings to be resolved correctly but I thought that I should include this information.

**Comment by bbc2** [comment]
I can reproduce this issue.  Your program should indeed print "bye".

**Comment by bbc2** [comment]
I've created an MR (#260) with a fix for the issue your reported.  If you want you can try it and let me know if it works for you.  Otherwise I'll just go ahead and merge it.
