### ISSUE TITLE
Windows os install this package error

### ISSUE THREAD

**Issue by FPGA1988** [theskumar/python-dotenv#198]
The error log is :
`
File "setup.py" line 5 , in<module>
    long_description = f.read()
UnicodeDecodeError : 'gbk' codec can't decode byte 0x9d in position 1560 : illegal mltibyte sequence
`

**Comment by rishabhsingh971** [comment]
@FPGA1988  Can you try changing [`with open(file) as f`](https://github.com/theskumar/python-dotenv/blob/master/setup.py#L8) to `with open(file, encoding='utf-8')` as mentioned in https://github.com/rkern/line_profiler/issues/37#issuecomment-356240626, to see if it works.

**Comment by adoconnection** [comment]
I probably have the same error on my old Windows 2008R2 machine:
 `pip install python-dotenv`

at some point gives me:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte (sitecustomize.py, line 21)

OS locale is RU

**Comment by BackMountainDevil** [comment]
win10 amd64 with py 3.9 is fine

**Comment by bbc2** [comment]
Is this still a problem? Our `setup.py` has been fixed to use a well-defined encoding a long time ago, so that it doesn't cause errors when using `pip install`.  I don't think we can do anything about errors coming from other files like `sitecustomize.py`.

**Comment by bbc2** [comment]
I'll close this as there is nothing I can do about it but feel free to reopen the issue if you have more information.
