### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by twosigmajab** [theskumar/python-dotenv#199]
It would be really helpful to have full API documentation for python-dotenv, showing just what is provided where.

If you use http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html this is merely a matter of making sure all public modules, classes, and functions have docstrings.

Thanks for your consideration!

**Comment by anshulxyz** [comment]
Hey, Saurabh, I'd like to help out on this. Let me know how far we've come in this.

**Comment by theskumar** [comment]
@anshulxyz Hi @anahulxyz , most probably no one has started on it yet. Feel free to start it by yourself. Thanks.

**Comment by anshulxyz** [comment]
@theskumar any examples you'd like to suggest to mimic for the docs?

**Comment by theskumar** [comment]
The API docs are available now at https://saurabh-kumar.com/python-dotenv/reference/dotenv/
