### ISSUE TITLE
document the format of ".env"

### ISSUE THREAD

**Issue by philippeluickx** [theskumar/python-dotenv#2]
I know it is silly, but got me confused for a minute...
I am used to doing "export VAR=value". So I was wondering which format the vars should be in.
Maybe dropping in a line on the README would help for us confused souls?

SECRET_KEY="your_secret_key"
...

BONUS:
When using django-configurations, prepend all vars with DJANGO_

DJANGO_SECRET_KEY="your_secret_key"

**Comment by theskumar** [comment]
:+1: happy to accept a pull-request, if you like. I'll get it done as soon as I can.

**Caution:* It's not **always** the case that you need to prepend KEY with DJANGO_, django-configuration allows to override this behaviour with `environ_prefix` and `environ_name` parameters. see: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/config/production.py#L103 for example.

Thanks for bringing this to notice! :)

**Comment by philippeluickx** [comment]
https://github.com/theskumar/python-dotenv/pull/3
