### ISSUE TITLE
Support source(bash) syntax like in ruby dotenv

### ISSUE THREAD

**Issue by roll** [theskumar/python-dotenv#20]
https://github.com/bkeepers/dotenv#usage

> You may also add export in front of each line so you can source the file in bash:

```
export S3_BUCKET=YOURS3BUCKET
export SECRET_KEY=YOURSECRETKEYGOESHERE
```

**Comment by theskumar** [comment]
Looks interesting, would be a nice addition.

**Comment by theskumar** [comment]
@roll well it seems it's quite easy to export variable using `source` command.

```
set -o allexport
source .env
set +o allexport
```

which is equivalent to:

```
set -a; source .env
```

**Comment by roll** [comment]
@theskumar 
Thanks, I was using the first one as additional file in a repo. But with the second version it short enough to be a comment on top of `.env.example` file. So for me it's enough, thanks.
