### ISSUE TITLE
`.flaskenv` not setting environment variables, incl. FLASK_ENV

### ISSUE THREAD

**Issue by vishrutarya** [theskumar/python-dotenv#200]
**Goal:** Automatically set environment variables for Flask using `python-dotenv` and a `.flaskenv` file in the top-level directory.

**Expected output:** Writing a `my_app/env_vars.flaskenv` file in the top-level directory with the following code [should set these two environment variables](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Flask.run):

```
FLASK_APP=my_app.py
FLASK_ENV=development
```

**Actual Output:** 
```
$ cd my_app
$ flask run
* Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
...
$ printenv FLASK_ENV
$ 
$ printenv FLASK_APP
$
```
Notice that, despite the `.flaskenv` file's existence and running the app, these two environment variables do not appear to be set, as evidenced by (1) the `flask run` output which states the environment is production (which changes if I _manually_ run `export FLASK_ENV=development`) and (2) the `printenv` commands which print nothing.

**Comment by bbc2** [comment]
Is this really an issue with Python-dotenv?  My impression is this is a Flask problem.

By the way, I wonder if `env_vars.flaskenv` is the right name for the env file.  Shouldn't it be just `.flaskenv`?

**Comment by vishrutarya** [comment]
I just tested your hypothesis and you seem to be right: it works when the filename only has the extension, i.e., is exactly `.flaskenv`. Thanks @bbc2 !
