### ISSUE TITLE
AttributeError: 'module' object has no attribute 'parse_dotenv'

### ISSUE THREAD

**Issue by CrazyByDefault** [theskumar/python-dotenv#201]
One of our services uses `dotenv.parse_dotenv()` to load the env file. While setting up staging, after installing python-dotenv, the `parse_dotenv` is missing. Our production server has the same environment, and the `parse_dotenv()` function works fine there. 

> Staging environment (`parse_dotenv()` failing)

Python version: `2.7.12`
python-dotenv version: `0.10.3`
OS: `Linux vengine-staging 4.15.0-1041-gcp #43-Ubuntu SMP Wed Aug 21 09:04:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

> Production environment (`parse_dotenv()` works)

Python version: `2.7.12`
python-dotenv version: `0.10.3`
OS: `Linux vengine-test-final 4.15.0-1036-gcp #38~16.04.1-Ubuntu SMP Tue Jun 25 15:30:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bbc2** [comment]
The `parse_dotenv` function no longer exists.  I think you would probably want to use `load_dotenv` or `dotenv_values` instead.
