### ISSUE TITLE
CLI: Better error message when omitting run

### ISSUE THREAD

**Issue by iddan** [theskumar/python-dotenv#203]
Many times I accidentally call the `dotenv` CLI like:
```
dotenv -f my.env python
```
The error I get is:
```
Usage: dotenv [OPTIONS] COMMAND [ARGS]...
Try "dotenv --help" for help.

Error: No such command "python"
```
I think an error that lists the available commands or suggests me to try adding `run` would be better especially because Ruby's `dotenv` doesn't require `run` and it is confusing for new users

**Comment by bbc2** [comment]
The behavior is consistent with other popular Python tools such as Pipenv and Poetry, so I wouldn't consider it confusing for Python users.  I think the error message clearly shows that the first word was interpreted as a command.  The user can run `dotenv --help` to see the list of commands.

Therefore, while the error message could probably be improved for this particular case, I don't think it's worth using it given the added complexity for other cases.
