### ISSUE TITLE
python-dotenv not working in pypy

### ISSUE THREAD

**Issue by motey** [theskumar/python-dotenv#209]
Not sure if i am right here. sorry if not.
I am trying to use python-dotenv with [pypy](https://www.pypy.org/).
installing with pip works fine, importing it in python not

`# docker run -it --rm pypy:3.6 /bin/sh`

```
# pip3 install python-dotenv
Collecting python-dotenv
  Downloading https://files.pythonhosted.org/packages/57/c8/5b14d5cffe7bb06bedf9d66c4562bf90330d3d35e7f0266928c370d9dd6d/python_dotenv-0.10.3-py2.py3-none-any.whl
Installing collected packages: python-dotenv
Successfully installed python-dotenv-0.10.3
# python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dotenv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'dotenv'
```
Anybody with the same issue?

**Comment by bbc2** [comment]
I think you are running CPython, not PyPy.  Try with the `pypy3` command instead of `python3`.

**Comment by motey** [comment]
Yep, that worked. Ok, i think i have a lack in understanding the concept of pypy. I thought of it as a drop-in replacement.
Thanks a lot for for pointing me in the right direction.
