### ISSUE TITLE
dotenv keeps '\r' at end of variables in django

### ISSUE THREAD

**Issue by rlkelly** [theskumar/python-dotenv#21]
Is it possible to strip my variables when I `from dotenv import load_dotenv` it keeps the trailing '\r' on my variables which is breaking my build and I have to manually update my variables or call `os.environ['env_variable'].strip()`.

How can I avoid this?

**Comment by theskumar** [comment]
Hi @rlkelly, not sure if you meant to close this. `.env` file support variables in quotes, so this problem shouldn't arise. Try storing the variables as:

```
foo="bar"
```

Yes, we can remove the `\r` or `\n` from the variables, but I would not advise on using `.strip()` which also removes blank spaces.
