### ISSUE TITLE
set_key doesn't escape values with quotes in them

### ISSUE THREAD

**Issue by soapergem** [theskumar/python-dotenv#215]
Suppose you have this code:

```python
import dotenv
import json

key = "KEY_TO_SAVE"
value = json.dumps({"test": "me"})
dotenv.set_key(".env", key, value)
```

What I would expect to see is a `.env` file that looks like this:

```
KEY_TO_SAVE="{\"test\": \"me\"}"
```

However what I actually see is this:

```
KEY_TO_SAVE="{"test": "me"}"
```

Because of the lack of escaping quote character, dotenv has effectively changed the value I was trying to set. In this case, the value passed to dotenv is valid JSON, but the value dotenv saves to the file is not valid JSON.

**Comment by bbc2** [comment]
Thank you for reporting this.  I can confirm that it's an issue with Python-dotenv and your expectations are sensible.  I'll work on a fix.
