### ISSUE TITLE
Either space or quote is not allowed in value, truncated otherwise

### ISSUE THREAD

**Issue by patkai** [theskumar/python-dotenv#218]
If there is a `space` in `value` then `quote_mode='never'` will truncate the string on read at the location of the first `space`. If, however, `quote_mode='always'` then the string can't include a quote, as the string will be truncated on read at the location of the first `"` inside of the string. I'm happy to fix this, unless it is a feature :)

**Comment by bbc2** [comment]
There are probably issues with the `dotenv set` command but I'm not sure what problem you're having.   Could you show me one or two examples?

**Comment by bbc2** [comment]
This might be fixed by #330 when it's merged. In case you'd like to test it, I'd be happy to know what you think about it.
