### ISSUE TITLE
Warning for consecutive lines that are comments

### ISSUE THREAD

**Issue by Harmon758** [theskumar/python-dotenv#223]
With #211 (v0.10.4), if there are consecutive lines that are comments, there will be a warning for each line after the first. because `key` and `value` will be `None`, passing the check for the warning. The only reason the first line does not have a warning is because it is considered as part of the line before, since the regular expression for comments captures any whitespace, including newlines, at the beginning.

**Comment by bbc2** [comment]
Thank you so much for reporting this.  It's indeed an issue and I think there would even be an unwanted warning with just one comment-only line.  I'm hoping that #224 will fix this.

**Comment by Harmon758** [comment]
Currently, just one comment-only line doesn't prompt a warning, for the same reason the first line in consecutive lines of comments doesn't.

**Comment by bbc2** [comment]
I think I see what you mean:

```
a=b
# comment
# comment
```

```
Python-dotenv could not parse statement starting at line 3
{'a': 'b'}
```

But I found out that just the following also causes a warning:

```
# comment
```

```
Python-dotenv could not parse statement starting at line 1
{}
```

Anyway, I think I fixed it with the latest MR. And I've also avoided the capture of newlines preceding comments so that debugging is easier.

**Comment by Harmon758** [comment]
That's what I meant, yeah. Thanks!
