### ISSUE TITLE
[bug] Lists in .env

### ISSUE THREAD

**Issue by filtration** [theskumar/python-dotenv#229]
I have a simple env file with a list for example:

**.env**

    tokens = ["thisistoken1", "thisistoken2"]

Now when I retreive it like so:

    print(os.getenv('tokens')[0])

It will return something like so:

> [

**Comment by theskumar** [comment]
`.env` file format doesn't support list as is. The values are always treated as string. The value you got in result is correct if you consider the value stored as result.

**Comment by theskumar** [comment]
If you really want to work with list then store them as comma separated value and parse the string to get a list.
