### ISSUE TITLE
Python-dotenv could not parse statement

### ISSUE THREAD

**Issue by loonfly** [theskumar/python-dotenv#235]
Hi Guys,

I use dotenv in my Django app and ran into one issue when i runserver:

`> Python-dotenv could not parse statement starting at line 10`

although the django seem working fine, but I couldn't feel right about this.

Here is my .env file:
```
DJANGO_SECRET_KEY="xxxxxxxxxxxxxxxxx"
DEBUG=True
DATABASE_DEFAULT_ENGINE="django.db.backends.postgresql"
DATABASE_DEFAULT_NAME="postgres"
DATABASE_DEFAULT_USER="postgres"
DATABASE_DEFAULT_PASSWORD="abc123"
DATABASE_DEFAULT_HOST="localhost"
DATABASE_DEFAULT_PORT="5432"
SENDGRID_API_KEY="xxxxxxxxxxxxxxxxxxxxxxxx"
```
And i have load the dotenv in wsgi.py:
```
import os

from dotenv import load_dotenv

from django.core.wsgi import get_wsgi_application

load_dotenv()

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'webapp.settings')

application = get_wsgi_application()
```

and i even done it in manage.py:
```
import os
import sys

from pathlib import Path

from dotenv import load_dotenv

env_path = Path('webapp') / '.env'
load_dotenv(dotenv_path=env_path)
... the rest as usual
```

is this a bug or my own mistakes?

**Comment by vshih** [comment]
I'm seeing this too.  It happens if the last line in the .env file is empty.

Some quick testing shows that it appeared in 0.10.4; with 0.10.3 no warning is displayed.

**Comment by bbc2** [comment]
This is indeed surprising. It looks like your .env is fine so Python-dotenv shouldn't output a warning.

Have you been able to test this on the latest version (v0.11.0) and maybe even on the master branch?  I've tried to reproduce the problem but couldn't (I don't see any warnings and the right values are parsed).

What version of Python are you using? Is it possible that there are some unexpected, invisible, characters after the last line of your .env file?

**Comment by bbc2** [comment]
Ah, I've been able to reproduce it.  I didn't see your comment about the last line being empty.  Is that also your case @loonfly?

I'll work on a fix.  Thanks for reporting!

**Comment by s2t2** [comment]
I can confirm the error goes away if last line of .env file is not empty. Thanks @vshih

**Comment by loonfly** [comment]
@bbc2  sorry sir i was busy this 2 weeks. just tested and double confirm it is the empty line below causes this error. I removed it and the error is gone. I am not sure if it the the autopep8 append the empty line for me. 

to answer your questions for your ref:
python 3.8.1
django 2.2.7
python-dotenv 0.11.0

thanks you guys awesome! thanks @vshih pointed out.

**Comment by bbc2** [comment]
Hi @loonfly.  Thanks for the report.  Version 0.12.0 of python-dotenv should have the fix for the empty line issue.
