### ISSUE TITLE
dotenv run breaks out of venv on windows

### ISSUE THREAD

**Issue by cnschn** [theskumar/python-dotenv#243]
On windows, for python versions 3.7.3 and higher, activating a virtual environment created with the `venv` module and executing `dotenv run something.py` does not use the correct, `venv` provided python interpreter, but the global one instead. For me, this breaks using `dotenv run` in poetry-managed projects to replace pipenv, which handles loading variables from `.env` files natively.

This is no direct fault of python-dotenv, but seems to happen because of [python issue 38905](https://bugs.python.org/issue38905), which describes the wrong interpreter being used in `subprocess` calls. I can confirm that simply using `subprocess.Popen` shows the same issues on the affected python versions for us.

Interestingly, this only applies to virtual environments created using `venv`, those created using the `virtualenv` package seem to be fine. Still we would like to keep using poetry which relies on `venv`.

Any ideas how to mitigate this, without having to downgrade python?

**Comment by jamesmyatt** [comment]
Try `python -m dotenv.cli run something.py`

**Comment by cnschn** [comment]
Same result. Anything else would have been quite weird, I mean, it's still using `subprocess` to execute the command.

**Comment by jamesmyatt** [comment]
I suppose so

**Comment by theskumar** [comment]
As far as I understand this is not really a problem with this library but issue with your python environment setup. Please do share what works for you, but sorry i've close this ticket.

**Comment by cnschn** [comment]
Well, I agree that the root cause is outside this library, but still this means that the `dotenv run` feature is broken for everyone using windows, python >= 3.7.3 and the native venv module. I would have expected this to affect more people, but maybe the `[cli]` extra isn't as widely used?

Anyway, a simple fix would be to run the subprocess with `shell=True`. Is this something you'd consider? I'm aware of the usual caveats of running through the shell, but I would argue that in this case it's viable.

**Comment by jeloagnasin** [comment]
@cnschn, how did you go about solving this issue?

**Comment by cnschn** [comment]
@jeloagnasin not at all, really. I'm mainly using WSL these days which doesn't have the issue, or use dotenv from inside the application instead of the `dotenv run` cli.
