### ISSUE TITLE
Feature request: Support multiple .env files based on environment?

### ISSUE THREAD

**Issue by nmodi** [theskumar/python-dotenv#246]
I'm not sure if this is already an existing feature. Is there a way to have multiple .env files in a repository in which an environment variable controls which is used? This could be useful in having a different .env file for dev, staging, and production. Alternatively, being able to do this in the same .env file would be useful as well if multiple files is not possible.

**Comment by bbc2** [comment]
A similar issue was raised in the past: #73.  Could you look into the suggestions and let us know if that helps you with your problem?

**Comment by nmodi** [comment]
Yes, that is a good solution, thank you!
