### ISSUE TITLE
Working without having settings.py

### ISSUE THREAD

**Issue by MattiooFR** [theskumar/python-dotenv#249]
Is it a normal behavior that by just installing the python-dotenv dependencies in my flask web app, when I do `flask fun` flask now get all the variable in my `.env` file with no issue, and no needs for having a `setting.py` file with `load_env()` ?

**Comment by bbc2** [comment]
Yes, it is normal: https://flask.palletsprojects.com/en/1.1.x/cli/?highlight=dotenv#environment-variables-from-dotenv.

**Comment by MattiooFR** [comment]
Okay great :D Thank you
