### ISSUE TITLE
path variables like tidle (~) don't get expanded

### ISSUE THREAD

**Issue by clayg** [theskumar/python-dotenv#250]
I use a `.env` file with pipenv [1] and I'd expected to have a variable that aliases a path from the current users home directory:

```
clayg@banana:~/Workspace/scratch/mytest$ env | grep -i mydir
clayg@banana:~/Workspace/scratch/mytest$ pipenv shell
Loading .env environment variables...
Launching subshell in virtual environment...
clayg@banana:~/Workspace/scratch/mytest$  . /home/clayg/.local/share/virtualenvs/mytest-GzP8C70q/bin/activate
(mytest) clayg@banana:~/Workspace/scratch/mytest$ env | grep -i mydir
MYDIR=~/Workspace/scratch/mytest
(mytest) clayg@banana:~/Workspace/scratch/mytest$ cd $MYDIR
bash: cd: ~/Workspace/scratch/mytest: No such file or directory
(mytest) clayg@banana:~/Workspace/scratch/mytest$ source .env
(mytest) clayg@banana:~/Workspace/scratch/mytest$ cd $MYDIR
(mytest) clayg@banana:~/Workspace/scratch/mytest$ echo $?
0
(mytest) clayg@banana:~/Workspace/scratch/mytest$ cat .env 
export MYDIR=~/Workspace/scratch/mytest
```

As a workaround I've noted I can use:

```
export MYDIR=${HOME}/Workspace/scratch/mytest
```

I'm confident python's expanduser [2] could be used for cross-platform expansion but I'm not sure where to apply it since the posix variable regex won't notice ~ and call the replacement method [3].

1. https://pipenv-fork.readthedocs.io/en/latest/advanced.html#automatic-loading-of-env
2. https://docs.python.org/2/library/os.path.html#os.path.expanduser
3. https://github.com/theskumar/python-dotenv/blob/784102284471252f418e797c1874a00063426210/src/dotenv/main.py#L233

**Comment by theskumar** [comment]
I'm not favour of adding this. This is very specific use case that can be handled at the application code level. 

If we do add this functionality of recognising this `~` then we would need another way to know that the value is really a PATH variable, else we will end up expanding a lot of values like password with home directory. 

Like you said, we already have support for recognising existing environment variable and that will help you do what is needed in a very readable way.
