### ISSUE TITLE
Proposed way to test app which uses python-dotenv

### ISSUE THREAD

**Issue by jugmac00** [theskumar/python-dotenv#253]
Hi,

I am thinking about using this library for one my apps.

Without this app, I can just set the environment variables via os.environ.

When I use this app and thus a `.env` file, do I have to patch `load_env`? Or would I put a test `.env` in the project root which gets collected by the `find_dotenv` function? How would I handle a dev env and my test env? Switch env files all the time?

Thanks for any hints.

**Comment by bbc2** [comment]
I'm not sure I understand your use case.  I recommend you have a look at the "Getting Started" section of the readme (https://github.com/theskumar/python-dotenv#getting-started).  Does it look like it could help you solve your problem?

**Comment by jugmac00** [comment]
When I follow the documentation....
```
# settings.py
from dotenv import load_dotenv
load_dotenv()
```
As `load_dotenv()` is at module level, it will always get called when I run tests, but I certainly do not want to check in a .env file in my repository.

So, with using this module, how do you propose to do a proper test setup?

Fake .env ? Or patch load_dotenv to load special values for the tests?

I am not 100% sure, but maybe now it is more clear.

**Comment by bbc2** [comment]
The example in the readme uses a `load_dotenv` at the module level but you can also use this function in another function if you want.

Using a fake `.env` would definitely work, but it might be simpler to just set environment variables before your test is run (when the `.env` is absent, `load_dotenv` does nothing).

I'm not sure what you are trying to test. Are you trying to test that the application uses `load_dotenv` correctly?  Or are you trying to test other parts of your app under a specific configuration?

**Comment by jugmac00** [comment]
Thank you for taking the time!

I try to test my application. The behavior depends on the values of the environment variables.

I never test third party code - I assume it is working correctly :-)

**Comment by billkouts** [comment]
Do you have only one set of env variables? I would guess not. 
For example, for development you might have
DATABASE_URL=path/to/local/db
And for production
DATABASE_URL=path/to/cloud/provider

For running the tests locally, you will have the .env filled with the development values in your local copy of your project.
No need to patch the load_env.

Also, add the .env file to gitignore and you should be fine

**Comment by jmussman** [comment]
Four years late to the party, but here is a better way:

load_dotenv() is a one-off, any subsequent calls are no-ops. If the code under test (CUT) is using load_dotenv, then the simplest way to mock the environment is to call it first from the test. Much easier than trying to patch it.

If you want to build unit tests with a different .env file, simply set it up in the test suite as load_dotenv(dotenv_path='some-path') and that will use the designated file. Again, when the CUT is invoked the function there becomes a no-op.

If you want to override environment variables for a particular test, call load_dotenv from the test and then change os.environ: add, remove, or modify dictionary entries. The changes will stick into the CUT.

One other note: some IDEs, VS Code in particular, will find and load the .env file when debugging Python, without using load_dotenv. If you want to change the file, you will need to disable this in the IDE. For VS Code look for Python: Env File in the settings, or make "envFile" in the launch configuration empty.
