### ISSUE TITLE
TypeError: argument should be string, bytes or integer, not PosixPath with README.md example

### ISSUE THREAD

**Issue by morgangraphics** [theskumar/python-dotenv#254]
Using the example in the README.md file as is:

```python
# OR, explicitly providing path to '.env'
from pathlib import Path  # python3 only
env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)
```

throws the `TypeError: argument should be string, bytes or integer, not PosixPath` error. 

I believe that the correct example should be:

```python
# OR, explicitly providing path to '.env'
from pathlib import Path  # python3 only
env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path.name)
```

**Comment by bbc2** [comment]
I tried your examples and both work on my machine.  What are your versions of Python and Python-dotenv?

**Comment by morgangraphics** [comment]
Python 3.5.2
python-dotenv 0.13.0

Directory Structure
```bash
<CURRENT_PROJECT>
   |--   config
   |      |--   .env
   |--   settings.py
```

Minimum example to produce error
```python
# setting.py
from dotenv import load_dotenv
from pathlib import Path

# Load .env file
env_path = Path('.') / 'config/.env'
load_dotenv(dotenv_path=env_path)
```

Working example

```python
# setting.py
from dotenv import load_dotenv
from pathlib import Path

# Load .env file
env_path = Path('.') / 'config/.env'
load_dotenv(dotenv_path=env_path.name)
```

**Comment by bbc2** [comment]
Thanks, I now see why it doesn't work for you.  It's because we use `os.path.isfile` internally and that function has only supported `Path` arguments starting from Python 3.6 (https://docs.python.org/3.8/library/os.path.html#os.path.isfile).

I'm not sure it will be worth fixing in our code, but I think we could update our readme to let users know the minimum Python version for the example to work.

**Comment by morgangraphics** [comment]
The working example above does work as stated so at the very least there is a workaround for older versions of Python. The update for the minimum version in the README.md is a reasonable compromise.
