### ISSUE TITLE
Feature proposal: .env.local and .env.[environment][.local]

### ISSUE THREAD

**Issue by mandrewcito** [theskumar/python-dotenv#257]
Hi,

Is there a way to deal with local configurations or environment dependent configurations?. 

I will explain my idea:

 On the process of developing an app, You would have  a .env  file stored on the version control with a default options (a template with default values). But when you are on the development process you need a .env.local. Why? becouse you need to store your DB conection string and other config values related with your local environment.  Next, on your publishing/test/stage scenario your connection strings will change so you will need a different environment file:

IMO the load secuence of the .env will be the follwing:

On development scenario:

- .env // default options
- .env.development // common development options
- .env.local

On the other scenarios:
- .env
- .env.[staging/production]

Is there a way to configure this behaivour on the library ? if is not do you have plans to add this behaiour? I ask this because i can add this functionality to the library and make a PR if you consider it useful.

**Comment by aniketmaithani** [comment]
@mandrewcito But don't you think this would over complicate things ? I mean first of all w.r.t convention only should we keep it `.env.local` or `.env.development` similarly if we have multiple pipelines before the release such as `dev` , `staging`, `qa`, `prod` , pouring out such a thing in this library would be un-necessary. Well that's my two cents. 

It would be good if we ask other contributors and devs to vote on this. 
also cc: @theskumar @bbc2  your take guys ?

**Comment by bbc2** [comment]
If you have default values for all environments, why not hard-code them in the application itself and override them with a different `.env` for each scenario?

I've seen similar feature requests in the past, regarding multiple scenarios.  Please have a look at https://github.com/theskumar/python-dotenv/issues/73 for a previous discussion.  Does it look like it could solve your issue?

**Comment by mandrewcito** [comment]
Yes,  in fact on my current apps im doing that way. Question was only for porouse a new  the a feature similar to vue environment variables behaviour (https://cli.vuejs.org/guide/mode-and-env.html#modes). If you consider it an unnecesary feature to you lib its ok :D 
Thank you !
