### ISSUE TITLE
Support for multi line environment variables

### ISSUE THREAD

**Issue by esa606** [theskumar/python-dotenv#26]
Similar to https://github.com/bkeepers/dotenv/issues/21

I have keys that include newlines, but python-dotenv can't read those. Similar to other solutions, a good solution might be to delimit newlines within quotes. Alternatively, a solution could involve preserving the newline character--currently read in by Python as '\\n'.

Is there any interest in such a PR?

**Comment by esa606** [comment]
Alternatively, a solution could involve the newline character--currently read in by Python as '\\n'

**Comment by iameugenejo** [comment]
PR #28

**Comment by theskumar** [comment]
Thanks @iameugenejo for the pull-request. Guys, this is in master now. Please try it out, will release this on pypi as part of the next release 0.6.0.

**Comment by chenchuk77** [comment]
Hi, sorry for the newbie question but im trying to check multiline functionality and cant get it work. I cant find this commit in git log on master branch. b61e91ab7f659b82dd67d2d28a37529cd5d47769
how its possible ? is it removed?
Thanks .

>  ~/python-dotenv/ git log | grep b61e91ab7f659b82dd67d2d28a37529cd5d47769
>  ~/python-dotenv/ 
>

**Comment by iameugenejo** [comment]
@chenchuk77 The change was re-commited later by @theskumar as ff92e1e34c1e5b5e3f55a2a9d9fad4948c631151

Please refer to issue #82 and see if that helps.
