### ISSUE TITLE
AttributeError: module 'typing' has no attribute 'Text'

### ISSUE THREAD

**Issue by gongqingkui** [theskumar/python-dotenv#261]
X;\venv\lib\site-packages\dotenv\parser.py", line 44, in <module>
    ("string", typing.Text),
AttributeError: module 'typing' has no attribute 'Text'

**Comment by bbc2** [comment]
What version of Python are you using?  If it's 3.4 or earlier, I'm afraid we don't support it.

**Comment by jjgutierrez0314** [comment]
Hello, I am also getting the same error. I am using Python 3.5.0

...
File "/mnt/nfs/exa/work/jjg/Microblog/venv/lib/python3.5/site-packages/dotenv/ parser.py", line 44, in                                                      ("string", typing.Text),                                                     AttributeError: module 'typing' has no attribute 'Text'

**Comment by gongqingkui** [comment]
> What version of Python are you using? If it's 3.4 or earlier, I'm afraid we don't support it.

I use Python3.5.1 in venv environment.
I fixed it with:
Change parser.py 58 line.
   except ImportError:
To
   except Exception:

It working.

**Comment by gongqingkui** [comment]
> Hello, I am also getting the same error. I am using Python 3.5.0
> 
> ...
> File "/mnt/nfs/exa/work/jjg/Microblog/venv/lib/python3.5/site-packages/dotenv/ parser.py", line 44, in ("string", typing.Text), AttributeError: module 'typing' has no attribute 'Text'

I use Python3.5.1 in venv environment.
I fixed it with:
Change parser.py 58 line.
  except ImportError:
To
  except Exception:

It working.

**Comment by gongqingkui** [comment]
The question has been resolved by @bbc2 in #267
