### ISSUE TITLE
find_dotenv() not finding .env file in cwd

### ISSUE THREAD

**Issue by johneast** [theskumar/python-dotenv#265]
dotenv version: 0.14.0
OS: Ubuntu
Python version: 3.6

It seems that python_dotenv is always using the path of the file that contains the call to `load_dotenv()` instead of the cwd.

We have a file structure similar to this
```
repo_root
    -- lib
        -- lib
             base_class.py
        .env
        Pipfile
    -- app
        -- app
             main.py
       .env
       Pipfile
```
So we have an application in one project/folder, using the base class defined in another project/folder. The PYTHONPATH of the application includes the path to the lib project. The virtual environment of the app contains all the dependencies defined in Pipfile.

The base class of the application contains the code for loading the environment variable. When I run the app from the folder `repo_root/app`, `find_dotenv()` finds the `.env` file in `repo_root/lib` (where the call to `load_dotenv()` actually is) instead of the cwd.

**Comment by bbc2** [comment]
I think this is what `load_dotenv` is supposed to do by default.  It calls `find_dotenv` which will search for the `.env` file in the same directory as the file, and then parent directories.  If you want to look in the current working directory, I think you can try `load_dotenv(find_dotenv(usecwd=True))`.   Does that work for you?

That being said, you might have been confused by the README, which says:

> [...] calling load_dotenv when the application starts, which will load environment variables from a file named .env in the current directory or any of its parents or from the path specificied

In that sentence, "current directory" should probably be replaced by "same directory as the file containing the `load_dotenv` call".

**Comment by johneast** [comment]
The docs are slightly confusing and it would be better if they were changed.

Called `find_dotenv(usecwd=True)` manually does indeed fix the issue. So Thanks.

**Comment by rceback** [comment]
Why choose the file's directory as the default start point instead of current working directory?
