### ISSUE TITLE
Python-dotenv could not parse statement starting at line 3

### ISSUE THREAD

**Issue by ben476** [theskumar/python-dotenv#266]
It doesn't seem to work when I have a . (full stop) in in one of the variables. It works perfectly fine when I remove the .

**Comment by bbc2** [comment]
I can't reproduce the issue. Could you show an example that causes the problem so that I can understand and try it?

**Comment by bbc2** [comment]
I'm closing this issue as there is no evidence that a problem exists in python-dotenv. Let us know if you have more information.
