### ISSUE TITLE
python-dotenv prevents launch of Flask server

### ISSUE THREAD

**Issue by qqgg231** [theskumar/python-dotenv#271]
When I have `python-dotenv` in `requirements.txt` Flask app will not run:

```
* Serving Flask app "source/app.py"
 * Environment: development
 * Debug mode: off
Usage: python -m flask run [OPTIONS]

Error: Could not import "app".
```

If I comment `python-dotenv` in `requirements.txt` and then recreate venv, then Flask app will run as usual

**Comment by TheBoringDude** [comment]
post your source code, it has no concern with running flask at all though

**Comment by vicchi** [comment]
Same experience here ... Python 3.8.5, Flask 1.1.2, python-dotenv 0.15.0 on Ubuntu 20.04 ...

This can be replicated with the following totally simplistic `test.py`

```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return {
        'hello': 'world'
    }
```

Creating an empty `virtualenv` and installing Flask and running the test case ...

```
$ virtualenv -p `which python3` venv
<snip>
$ source venv/bin/activate
$ pip install Flask
<snip>
$ pip freeze | grep Flask
Flask==1.1.2
$ FLASK_ENV=development FLASK_APP=test.py flask run --host=babbage.home.vicchi.org --port=6001
 * Serving Flask app "test.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://babbage.home.vicchi.org:6001/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 616-909-873
```

At this point hitting the Flask app on port 6001 in browser or via Postman yields the expected JSON payload. 

```
172.20.0.98 - - [10/Dec/2020 15:41:58] "GET / HTTP/1.1" 200 -
```

Now kill the app and install `python-dotenv`, the Flask app code doesn't change and `dotenv` isn't imported at all, just installed into the virtualenv ...

```
$ pip install python-dotenv
Collecting python-dotenv
  Downloading python_dotenv-0.15.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-0.15.0
```

Again, run up the Flask app and hit the same endpoint. This time ...

```
$ FLASK_ENV=development FLASK_APP=test.py flask run --host=babbage.home.vicchi.org --port=6001
 * Serving Flask app "test.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://babbage.home.vicchi.org:6001/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 616-909-873
172.20.0.98 - - [10/Dec/2020 15:47:11] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gary/Projects/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/gary/Projects/venv/lib/python3.8/site-packages/flask/cli.py", line 97, in find_best_app
    raise NoAppException(
flask.cli.NoAppException: Failed to find Flask application or factory in module "test". Use "FLASK_APP=test:name to specify one.
```

Doing a `pip uninstall python-dotenv` and everything works again and I have absolutely no idea why

**Comment by vicchi** [comment]
Quick update ... in case of a corrupted cache I nuked mine via `pip cache purge`, reinstalled `python-dotenv` and tested with no change. I also built the `python-dotenv` wheel from scratch in case of upstream corruption there, via `pip install python-dotenv --no-binary :all:` and retested, but again, no change in the behaviour.

**Comment by bbc2** [comment]
That's weird.  Is there a `.env` or `.flasken` file in your project?

It looks like this problem has more to do with Flask than python-dotenv but if there's a problem in python-dotenv, I would be happy to look into it.

**Comment by vicchi** [comment]
@bbc2 No but also ... _very_ interesting. If I re-install `python-dotenv` into my virtualenv and drop a overly simplistic `.env` containing just `FOO=bar` into the same root directory as my Flask app, I _don't_ get the `flask.cli.NoAppException` raised.

But if I move the `.env` file up one level (or several levels) of directory, then I immediately get `flask.cli.NoAppException` raised.

Uninstall `python-dotenv`, the exception goes away. Reinstall and the exception comes back for any directory (all the way back up to `/`) above the working directory that have a `.env` file in them.

Yet I'm not even importing `dotenv` let alone invoking a single module method.

That sound you can hear is me scratching my head.

So there is some interaction between Flask and `python-dotenv` going on here, presumably in either Flask's or this module's `__init__.py` which is barfing when a `.env` is found up the directory hierarchy. But what or how still eludes me.

**Comment by vicchi** [comment]
I think this is a clash between Flask's lazy loading and `python-dotenv` somehow ... I can trigger the behaviour even with an empty `.env` file one level up from the directory Flask is running in. Though I can't see anything in `./src/dotenv/__init__.py` that's immediately obvious but having said that, some of the way in which Python's module system works is still arcane knowledge to me.

**Comment by vicchi** [comment]
So _definitely_ a lazy loading clash. If I explicitly run Flask via Gunicorn, thereby bypassing the Flask development server lazy loading with `gunicorn --bind 0.0.0.0:6001 test:app` and with `python-dotenv` installed but not imported _and_ with an empty `.env` file one level up, the exception doesn't get raised.

**Comment by vicchi** [comment]
Buried in Flask's docs ... https://flask.palletsprojects.com/en/1.1.x/cli/#environment-variables-from-dotenv

> If python-dotenv is installed, running the flask command will set environment variables defined in the files .env and .flaskenv. This can be used to avoid having to set FLASK_APP manually every time you open a new terminal, and to set configuration using environment variables similar to how some deployment services work.
> 
> Variables set on the command line are used over those set in .env, which are used over those set in .flaskenv. .flaskenv should be used for public variables, such as FLASK_APP, while .env should not be committed to your repository so that it can set private variables.
> 
> Directories are scanned upwards from the directory you call flask from to locate the files. The current working directory will be set to the location of the file, with the assumption that that is the top level project directory.
> 
> The files are only loaded by the flask command or calling run(). If you would like to load these files when running in production, you should call load_dotenv() manually.

**Comment by vicchi** [comment]
And also https://flask.palletsprojects.com/en/1.1.x/cli/#disable-dotenv

Running as `FLASK_SKIP_DOTENV=1 FLASK_ENV=development FLASK_APP=test:app flask run --host=babbage.home.vicchi.org --port=6001` works perfectly. So I suspect this is down to how Flask runs `python-dotenv` whilst in development mode rather than `python-dotenv`. But I'll dig around in Flask's GitHub issues to see if there's anything reported and if not, open up an issue there.

What a journey of discovery!

**Comment by bbc2** [comment]
There isn't anything we can do at this point so I'll close this.  Let us know if you have more information and would like to reopen it.
