### ISSUE TITLE
Default and local env file

### ISSUE THREAD

**Issue by Saphyel** [theskumar/python-dotenv#272]
I was thinking it could be possible to make this module read the .env file but if you have .env.local or maybe .env.local or other files they will be loaded on top.
The advantages of this approach are:

- You can commit in your project .env file

- In scenarios where you can not change the .env file or the env. vars. you have the flexibility to add a new file and will be loaded on top.

- Your production code will be like your local.

The only disadvantage I can think of is

- A small logic needs to be implemented.

**Comment by bbc2** [comment]
We've seen similar feature requests in the past, regarding multiple scenarios. Please have a look at #73 for a previous discussion. Does it look like it could solve your issue?

**Comment by Saphyel** [comment]
@bbc2 thanks for the comment but it's not what I request (but similar!) 
```
    dotenv_file_list = []
    for file in os.listdir("./"):
        if file.startswith(".env"):
            dotenv_file_list.append(file)
    load_dotenv_files(dotenv_file_list)
```

**Comment by bbc2** [comment]
I think that with some code like the following, you program should work as you want:

```python
for file in dotenv_file_list:
    load_dotenv(file)
```

We're not likely to implement this logic in Python-dotenv itself because there are too many different use cases requested by users.

**Comment by bbc2** [comment]
I'm closing this issue because there doesn't seem anything we'll in python-dotenv with regards to this issue.
