### ISSUE TITLE
[Question] How to load from custom myConfig.env instead of default .env file?

### ISSUE THREAD

**Issue by scheung38** [theskumar/python-dotenv#274]
As Jupyter does not display these hidden .env files, unless I do 

jupyter notebook. --generate-config

which generates 

.jupyter/jupyter_notebook_config.py

config file to allow display of hidden files with

- Allow access to hidden files
#c.ContentsManager.allow_hidden = False

but we dont have vi or vim to open file inside Ubuntu, no vi or vim

**Comment by bbc2** [comment]
I'm not sure I understand your issue.  Is it possible for you to write `load_dotenv("myConfig.env")` in your code?  If so, that should fix your issue.

**Comment by dmbaker** [comment]
Would this also be the solution if one has a virtual environment is a directory named .env?

**Comment by bbc2** [comment]
Yes, it should also work in your case.
