### ISSUE TITLE
how to use 2 files in django on same directory

### ISSUE THREAD

**Issue by Hamza-Lachi** [theskumar/python-dotenv#280]
I have created 2 files named dev.env and prod.env

now when I try to run my code i get none
```

from dotenv import load_dotenv


load_dotenv(os.path.join(BASE_DIR, "dev.env"))
print(os.getenv("DEBUG"))
```

when i print debug i get none

it's mean it is not loading env variables

**Comment by bbc2** [comment]
I think this should work. Could you provide more information so that I can reproduce the issue?  For instance, the value of `BASE_DIR` and the content and location of `dev.env` and you Python file would be good to know.

**Comment by bbc2** [comment]
I'm closing this for now as we'd need more information to understand if there really is an issue in python-dotenv. Let us know if you have more information.
