### ISSUE TITLE
command parameters like nconf?

### ISSUE THREAD

**Issue by chadbr** [theskumar/python-dotenv#281]
Hello,

I've use a node package called 'nconf' for a number of years... 

It allows you to have 3 levels of parameters:
-environment,
-files,
-command line parameters

I was wondering if python-dotenv supported passing command line parameters to supplement / override the .env files? Am I missing it or is it simply not there?

Thanks much! Chad

https://www.npmjs.com/package/nconf for reference

**Comment by bbc2** [comment]
Python-dotenv is not really a configuration system.  It's mostly useful to help developers work with application taking their configuration from the environment (12-factor apps). It can do some other things be we try to limit its features to facilitate the maintenance of this package.

> I was wondering if python-dotenv supported passing command line parameters to supplement / override the .env files? Am I missing it or is it simply not there?

It's not there and probably will never be.  However, I think you can kind of achieve this by setting environment variables in the command line to override those in a `.env` file.  E.g: `FOO=BAR ./app.py`.

**Comment by bbc2** [comment]
I hope I have clarified the situation.  I'll close this issue for now as there is nothing I can do about it.
