### ISSUE TITLE
Can't run flask application with .env file in parent directory

### ISSUE THREAD

**Issue by vitaliy-diachkov** [theskumar/python-dotenv#284]
I've described issue here https://github.com/vitaliy-diachkov/flask-poetry-dotenv-issue-example, please. Firstly, I thought it was a poetry issue, but this problem only happens when I'm calling `load_dotenv()` in src/settings.py and .env file is in a parent (project root) directory.

**Comment by vitaliy-diachkov** [comment]
The issue was caused by Flask, as if you have `python-dotenv` installed it uses it to populate environment with variables from `.env` file, what was done manually by me in `src/settings.py` file and that caused issue.

**Comment by bbc2** [comment]
Thanks for the report, that's interesting.

If you want to use your own source of environment variables you might need to use a different name for the file (i.e not `.env`) and pass that name as an argument to `load_dotenv`. You might want to combine it with `find_dotenv` in order for the env file to be found up in the filesystem hierarchy.
