### ISSUE TITLE
Consider splitting requirements.txt into 2 files real requirements for runtime and dev requirements

### ISSUE THREAD

**Issue by bubak4** [theskumar/python-dotenv#286]
I think it is a good idea to keep dependencies minimal.  I like your project, but the dependencies for production usage keep installing packages like tox, pytest and such which are totally not required for runtime, only for testing and development.  Would you consider to create two separate requirements files?

**Comment by bbc2** [comment]
How do you install python-dotenv?  The dependencies in `setup.py` are minimal and only those should be installed in production.

**Comment by bubak4** [comment]
I would install python-dotenv using pip for my project, but I do not wish to install libraries for development. I think that for runtime, i definitely do not need tox, wheel, pytest or twine, still you have those dependencies installed.

**Comment by bbc2** [comment]
I'm afraid I don't understand your issue.  Python-dotenv doesn't have any declared mandatory dependency.  Again, you can check `setup.py`.  No extra dependency should be installed when you do `pip install python-dotenv`.

The file you referred to, `requirements.txt`, is only used by python-dotenv developers at the moment.

**Comment by phmccarty** [comment]
It is a common convention to see `requirements.txt` read by `setup.py` to add package runtime requirements, so this caught me off-guard, too. But after inspecting `setup.py`, I see that `requirements.txt` is irrelevant for production use at the current time.

So, perhaps this change could be considered in the future?

**Comment by bubak4** [comment]
Ok, thanks for clarification, I did not looked into setup.py, only into requirements.txt and that left me with wrong impression.  My bad, though as @phmccarty states, the requirements.txt and setup.py are usually used together with setup.py containing line like `install_requires=list(filter(lambda x: x, open("requirements.txt").read().split("\n")))` so this setup might be a bit more transparent imho.
