### ISSUE TITLE
set_key of hidden .env file

### ISSUE THREAD

**Issue by n4arora** [theskumar/python-dotenv#288]
I noticed that if the .env file is hidden, the set_key function was **unable to add/update the environment variables**. I think this should not be the case, if the **load_dotenv** function is able to load the hidden file, set_key should also be able to update the file.

**Comment by bbc2** [comment]
What does it mean for a .env file to be hidden?   Are you using Windows?

**Comment by n4arora** [comment]
Yes, I'm using Windows and in properties you can hide a file. When it's hidden, the set_key function is unable to update the .env file but you can still load it. It's probably accessed in a read-only mode.

**Comment by munivinayk** [comment]
I am facing similar problem in Mac. set_key doesn't update the .env file from frontend python script.

**Comment by theskumar** [comment]
This looks like an operating system-level file-permission issue that this library will not be able to resolve. 

Please open a PR with a fix if you think your issue can be solved by python-dotenv. Thanks for using this library. 🙌🏼
