### ISSUE TITLE
CLI run command argument conflict

### ISSUE THREAD

**Issue by shawnwall** [theskumar/python-dotenv#290]
I've created several CLI pythons scripts that utilize `click`, lets call one `test.py`. `click` itself uses `--help` as a default parameter to get help info. The `dotenv` CLI also has a `--help` argument. Running something like:

`dotenv -f ../.env run python test.py --help` 

...results in the `--help` argument getting used by `dotenv`, not my script. 

1. Is this intentional, or would this be considered a bug?
2. Is there a workaround (besides leaving off `--help` to default to click's help msg)?

**Comment by bbc2** [comment]
What about `dotenv -f ../.env run -- python test.py --help`?  `--` is a common convention to separate options and arguments for the program and click, which we use in python-dotenv, understands that convention.

**Comment by shawnwall** [comment]
@bbc2 that worked, thank you very much for your help.
