### ISSUE TITLE
Covert from str to bool if there is bool in .env file. Code included to fix it

### ISSUE THREAD

**Issue by nh916** [theskumar/python-dotenv#291]
In my .env file I placed 

**DEBUG = True** 

and I expected to be able to get the _boolean_ value out when I tried to get it with os.getenv("DEBUG")  it gave me type of _string_ which would always be truthy as long as it is not empty. 

I thought it would be great to have the ability to easily convert between _string_ to _boolean_ and python-dotenv should have a built in function that automatically does this. Since I could not find that function, I created one

```python

def string_to_boolean(value):
    if value == 'True':
        return True
    if value == 'False':
        return False
```

**Comment by bbc2** [comment]
This is interesting but is out of scope for the library, at least for now.

Your function is quite good but, in a library, it would be better to accept values in lowercase, and many other details like that.  It's not trivial and I don't want to invest time in a new library right now.

**Comment by Frick-David** [comment]
@nh916, I looked into this as well. @bbc2  is quite correct. The solution is what you have coded or use
```
bool(distutils.util.strtobool(some_string))
```
which is a pretty standard way of converting it.

**Comment by guettli** [comment]
I created a pull request to the README to make this more visible: 

https://github.com/theskumar/python-dotenv/pull/293

**Comment by Smlep** [comment]
Hey, I implemented https://github.com/theskumar/python-dotenv/pull/296, it should be what you are looking for

**Comment by bbc2** [comment]
Parsing strings into usable values of other types is not trivial and, as stated before, I don't want to undertake such a project in python-dotenv.  Maintaining a reliable .env parser is already a significant task.

To give you a sense of what parsing strings would entail, here are a few questions that it would raise:

- What format to accept?  Should we support multiple formats (e.g `True`, `true`, `1`) or just accept one?
- What to do if there is an error?  If we report the error, how to make it easier for the user to fix it?
- Detect format of each variable automatically or force the user to define a schema, a format for each variable? 
- To what type should each string be converted to?  For booleans it's easy but it's not trivial for other values like integer/floats, dates, etc.
- Where to draw the line between formats we enable support for and those for which we don't?  There's a potential for feature creep here.

**Comment by brianbruggeman** [comment]
One option is to include a way of passing in a callback to do the type conversion with a set of default ones that dotenv already provides.  That makes it easy to have a rather sane default and allow for someone to update as desired for a variety harder to tease out types.

But, "I don't want to do it" doesn't feel like a good response especially given that you actually have help and there have been at least one or two pull requests.

**Comment by guettli** [comment]
I still think this small path to the README would help: https://github.com/theskumar/python-dotenv/pull/293

---

### Converting types

The library reads and provides strings. If you need for example a boolean, it is up to you to convert the value.

Example:

```python
from distutils.util import strtobool
DEBUG = bool(strtobool(os.getenv('DEBUG', 'True')))
```
