### ISSUE TITLE
Environment variable persistence after script runs

### ISSUE THREAD

**Issue by Per48edjes** [theskumar/python-dotenv#295]
This is a handy little tool -- thanks for maintaining it!

Is the intended behavior of `load_dotenv` **not** to have the environment variables persist _after_ the execution of a Python script or module?

Here are the steps that led me to that conclusion:

1. Intend to have `DATA_PATH` available as an env variable. Run `echo $DATA_PATH` in `zsh` (on Mac OS X 10.15); nothing is returned as expected. I create `.env` and add `DATA_PATH="some/path/to/data"`.
2. `pipenv` is my virtualenv manager and I disabled `pipenv`'s [option](https://pipenv-fork.readthedocs.io/en/latest/advanced.html#configuration-with-environment-variables) to automatically source `.env` files upon activation so I'm entirely reliant on `python-dotenv` to load/get `DATA_PATH`.
3. Entered the virtualenv and ran my script (which calls `load_dotenv(override=True, verbose=True)`); everything ran fine (read: `DATA_PATH` _had_ to have been created for script to run properly). 
4. In my shell and still in my virtualenv, I `echo $DATA_PATH`...but nothing is returned (as in step 1)!

Do let me know if I'm missing something!

**Comment by bbc2** [comment]
I think this is the expected behavior.  The modifications done by `load_dotenv` only have an effect in the script that calls it, not in the parent shell. This is the same behavior as a Bash script modifying the environment: it doesn't affect the parent script (unless the parent called the script with `source`).

**Comment by Per48edjes** [comment]
Gotcha. Thanks for clarifying that, @bbc2. Will close the issue.
