### ISSUE TITLE
Cannot import name 'load_dotenv' from 'dotenv'

### ISSUE THREAD

**Issue by CubeBlazer** [theskumar/python-dotenv#298]
When I'm calling load_dotenv(), I'm getting this error:
```
Python 3.8.7 (default, Dec 26 2020, 21:09:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import dotenv
>>> dotenv.load_dotenv()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dotenv' has no attribute 'load_dotenv'
>>> 
```
I have also imported load_dotenv from dotenv:
```
Python 3.8.7 (default, Dec 26 2020, 21:09:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dotenv import load_dotenv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'load_dotenv' from 'dotenv' (unknown location)
>>> 
```
Running this on Raspberry Pi OS
I am not having any issues on Windows 10

**Comment by bbc2** [comment]
Could you try `print(dotenv)` to see where the module comes from?  I suspect it's not the module provided by python-dotenv.

It would also be useful to know how you installed python-dotenv and what version.

**Comment by CubeBlazer** [comment]
I found that it's not returning what I am expecting:
```py
>>> import dotenv
>>> dotenv
<module 'dotenv' (namespace)>
>>>
```
(namespace) should be replaced with the directory

When I run on Windows, it's as such:
```py
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dotenv
>>> dotenv
<module 'dotenv' from 'C:\\Users\\...\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\dotenv\\__init__.py'>
>>>
```
I installed python-dotenv using this command: `python -m pip install python-dotenv`
This is the version
```
pi@CBZR-server:~ $ python -m pip freeze
...
...
...
...
...
...
...
...
...
...
...
python-dotenv==0.15.0
...
```

**Comment by CubeBlazer** [comment]
Checking through my file directory, I am missing __init__.py in my installation. I copied __init__.py to the package and it works now.

**Comment by 0VERRIDER** [comment]
As an information for future references, It mostly causes because of the venv caching, primarily when you migrate from `dotenv` to `python-dotenv`. How ever, clear the venv cache (optionally delete the `.venv` folder and re-execute the virtaulenv ) and make sure  `__init__.py` is present in appropriate locations.
