### ISSUE TITLE
Add --replace flag to run command

### ISSUE THREAD

**Issue by zueve** [theskumar/python-dotenv#302]
As a developer i need usually quick change environment, without changing .env file. That's why I need replace some parameters by fly.What should i do:

Without -r flag:
> devenv run env | grep PORT
PORT=8000

With -r flag:

> PORT=5000 devenv run -r 0 env | grep PORT
PORT=8000

**Comment by zueve** [comment]
https://github.com/theskumar/python-dotenv/pull/303

**Comment by colllin** [comment]
Can you just `dotenv run PORT=5000 env | grep PORT` (move override into [COMMAND] instead of prefixing)?  Or I take it you want to override from outer ENV?  Then maybe you can do `dotenv run PORT=$PORT env | grep PORT`?

**Comment by zueve** [comment]
I use python-dotenv in Makefile and sometimes wants to change Environment like:

> PORT=1222 make start
