### ISSUE TITLE
dotenv get 'key' returns both key and value, not just key

### ISSUE THREAD

**Issue by EliiseS** [theskumar/python-dotenv#307]
When trying to get the value of a key in my `.env` file with `dotenv get` I am returned both key and value, despite the description for `dotenv get` saying it'll return the value:

```bash
17:42 # dotenv get --help
Usage: dotenv get [OPTIONS] KEY

  Retrieve the value for the given key.

Options:
  --help  Show this message and exit.
```

## Reproduction

```bash
# .env file
MY_KEY="my_value"
```

### Expected

```bash
dotenv get MY_KEY
my_value
```

### Actual

```bash
dotenv get MY_KEY
MY_KEY=my_value
```

**Comment by bbc2** [comment]
I agree this is not very practical.  I'll look into changing this despite the fact that it could be a breaking change.

**Comment by EliiseS** [comment]
Thanks for replying so quickly and making a PR already, that's really nice
