### ISSUE TITLE
Stream as any text file?

### ISSUE THREAD

**Issue by lmmarsano** [theskumar/python-dotenv#308]
As noted before
#208
#156
the code spec
https://github.com/theskumar/python-dotenv/blob/a7fe93f6cc73ab9de28191e3854f1a713d53363b/src/dotenv/main.py#L301
is unusually restrictive.
It'd be useful to accept any text file as a stream.
My use case would be packaging a `.env.defaults` file opened by [importlib.resources.open_text](https://docs.python.org/3/library/importlib.html#importlib.resources.open_text), so you can uniformly manage/document environment & defaults via `.env` files.

**Comment by linclelinkpart5** [comment]
Yes, I agree with this change. Having to slurp up the contents of the `.env` file in order to immediately repackage it as a `StringIO` is awkward and prohibits lazy loading of files. I'd love to instead be able to do this:

```python
dotenv_fp = Path('path/to/.env')
with dotenv_fp.open('r') as f:
    config = dotenv.dotenv_values(stream=f)
```

**Comment by bbc2** [comment]
I've created #348 to fix this. Let me know if there's any problem with that PR.  Otherwise I'll merge it in a few days.
