### ISSUE TITLE
The dotenv_values() method does not output values.

### ISSUE THREAD

**Issue by DigitalWolf98** [theskumar/python-dotenv#310]
**Hello everyone 👋**

When loading a .env file from another directory,
calling the dotenv_values() method returns an empty dictionary.

**App structure where everything works well:**
``` Bash
\http_public\
├─── \assets\
├─── \modules\
├─── .env
├─── __init__.py
└─── main.py
```

**Output with `dotenv_values()`:**
``` Bash
{'string_key': 'hello', 'digit_key': '2021', 'bool_key': 'True'}
```

**Output with `os.getenv("digit_key")`:**
``` Bash
2021
```

But if I move the .env to another directory (outside of `http_public`),
the dotenv_values() method doesn't return any values.
Although all values are successfully output using - `os.getenv()`

``` Bash
\root_user\
├─── \http_public\
│   ├─── \assets\
│   ├─── \modules\
│   └─── __init__.py
└─── \secret_folder\    
    ├─── .env
    └─── config.py
```

``` Python
# Importing packages
import sys
import os
from dotenv import load_dotenv, dotenv_values

# Set up environment variables
load_dotenv(
	dotenv_path = os.path.join(sys.path[0], os.path.pardir, "secret_folder", ".env")
)

# Output
print(dotenv_values())
```

**Output with `dotenv_values()`:**
``` Bash
{}
```

**Output with `os.getenv("digit_key")`:**
``` Bash
2021
```

**Comment by bbc2** [comment]
I'm not sure I fully understand your problem but I think I can provide useful information.

`load_dotenv` loads environment variables from a `.env` and writes them to `os.environ` so that you can access the variables as if they came from the real environment.

`dotenv_values` just loads variables from the `.env` file and returns a dict.

It is very unusual to use the two functions.  Usually, you use one or the other.

In your case, I think that `dotenv_values` can't find the `.env` file because it is in a different directory.  If you want to keep using `dotenv_values`, I think that you'll need to help it find the file like you did for `load_dotenv` with the `dotenv_path` argument.  Does that make sense?

**Comment by DigitalWolf98** [comment]
**Good afternoon!**
Thank you for trying to help, but you've described all the things I've already done.
Perhaps it is my fault that I did not describe everything in such detail... When opening this problem, I thought that this is not so necessary, because the documentation clearly says how to download `.env` files.

My problem is _(as I described in my first post when opening this problem)_ that if you move the file itself `.env` to any neighboring directory _(another branch)_, and load it with the help of specifying the `dotenv_path` parameter, then it perfectly loads all the specified variables into the list - `os.environ`, but when trying to get the same thing through the built-in `dotenv_values()` method, this method returns for some reason an empty dictionary, although it should return essentially the same as the `os.environ` list.

**Comment by bbc2** [comment]
> when trying to get the same thing through the built-in dotenv_values() method, this method returns for some reason an empty dictionary

Just to be sure I understand the problem, have you tried the following?

```python
dotenv_values(
	dotenv_path=os.path.join(sys.path[0], os.path.pardir, "secret_folder", ".env")
)
```

> although it should return essentially the same as the os.environ list.

No, `dotenv_values` should return a `dict` representation of the `.env` file that it finds not `os.environ`.

**Comment by DigitalWolf98** [comment]
Yes, I did, but the `dotenv_values()` method does not return anything, while `os.environ` has in its list the values that this method should return - `dotenv_values()`.

**Comment by DigitalWolf98** [comment]
Thank you for your help, I understood the policy of the developer of this library. I have to find something else, the library where the author has a more responsible attitude to his product in the face of other developers. I no longer want to deal with such a product that depends only on the "will" of the author himself, and not to bring something new and useful from issues queries.
