### ISSUE TITLE
dotenv command not found with pip3

### ISSUE THREAD

**Issue by Kamoba** [theskumar/python-dotenv#311]
I'm no more able to run dotenv command, i guess it's because dotenv get updated with some changes.
Always having: `dotenv command not found`.

Anyway i found the way to use it:
Before:
` dotenv  set USER=foo`
Now:
`python-dotenv set USER=foo`
And you have to reinstall dotenv with cli  `pip3 install "python-dotenv[cli]"`

If I have not misunderstood, the document must be updated accordingly.

**Comment by bbc2** [comment]
The command provided by this package (python-dotenv) should be called `dotenv`.  In what version of the package did you see a `python-dotenv` command?

**Comment by Kamoba** [comment]
May be actually i'm calling the one from linux got by `sudo apt-get python3-dotenv`.
I install that because only using `pip3 install "python-dotenv[cli]"` will not allow me to use cli, i do not not why.

**Comment by Kamoba** [comment]
Ok i found the problem:
the commade dotenv will not work with `pip3` i uninstalled pip on my light pi system and use only pip3 for all my modules and everthing work well.
But it's look like dotenv need some staff from pip which are not wvailable on pip3.
So `sudo apt-get install python-pip && sudo pip install "python-dotenv[cli]"` instead of `pip3 install "python-dotenv[cli]"` solve my problem.
Would be nice to have same thing with pip3.
Any idea how to do it with pip3?

**Comment by bbc2** [comment]
It should work with pip3.  You'll probably have to find where pip3 installs the `dotenv` executable.  If you activate a virtualenv, it will install it in the virtualenv directory.  I wouldn't recommend using `sudo pip install` as it could modify system files without going through the package management system.
