### ISSUE TITLE
No module named 'dotenv'

### ISSUE THREAD

**Issue by spamz23** [theskumar/python-dotenv#314]
When using this library locally (development) it works.
However, when it's being deployed to a server, it shows the following (when running Django `python manage.py migrate`):
```python
File "/home/spamz23/actions-runner/backend/aautad_pt/aautad_pt/backend/aautad/settings/dev.py", line 1, in <module>
    from .base import *
  File "/home/spamz23/actions-runner/backend/aautad_pt/aautad_pt/backend/aautad/settings/base.py", line 16, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

The strange part is that `python-dotenv` is added to requirements, like so:
```
# in requirements.txt
...
python-dotenv==0.16.0
...
```

The CI is also installing the library:

![image](https://user-images.githubusercontent.com/49190578/113067846-08f03480-91b5-11eb-88cc-0c612244d111.png)

But then at the moment of migrations, I get the module not found error.

Happening on Ubuntu
Any help?

**Comment by bbc2** [comment]
It's hard to say where the problem could come from.  Is python-dotenv the only package you use in `manage.py`?  My guess would be that the CI doesn't install the package in the same environment as that used to run migrations.

If the problem doesn't seem to come from python-dotenv, I would advise asking your question on a forum or mailing-list where Python and Django users will be able to assist you.

**Comment by bbc2** [comment]
Since there doesn't seem to be anything we can do to help, I'll close this issue.  Let us know if you have more information about this.
