### ISSUE TITLE
Poetry/PyPI issue getting info for python-dotenv  (0.17.1)

### ISSUE THREAD

**Issue by jasonk-specialized** [theskumar/python-dotenv#320]
I'm using Poetry as my package manager and attempting to roll python-dotenv to 0.17.1 hangs when solving for dependencies.

I'm not sure if this is a PyPI problem or if something changed in 0.17.1

Functional when: `python-dotenv = "0.17.0"`

Fails when:`python-dotenv = "0.17.1"`

Running `poetry update -vvv` with 0.17.1 will hang with the message below.
```
PyPI: 1 packages found for python-dotenv 0.17.1
PyPI: Getting info for python-dotenv (0.17.1) from PyPI
```

**Comment by bbc2** [comment]
Is this still an issue?  I'm unable to reproduce the issue. I tried:

```bash
$ poetry init   # no dependencies
$ poetry add python-dotenv==0.17.0
$ vim pyproject.toml  # to set version of python-dotenv to 0.17.1
$ poetry update -vvv
Using virtualenv: /home/bertrand/.cache/pypoetry/virtualenvs/ptryenv-dMFMY4Q7-py3.9
Updating dependencies
Resolving dependencies...
   1: fact: ptryenv is 0.1.0
   1: derived: ptryenv
   1: fact: ptryenv depends on python-dotenv (0.17.1)
   1: selecting ptryenv (0.1.0)
   1: derived: python-dotenv (==0.17.1)
PyPI: 1 packages found for python-dotenv 0.17.1
PyPI: Getting info for python-dotenv (0.17.1) from PyPI
   1: selecting python-dotenv (0.17.1)
   1: Version solving took 0.028 seconds.
   1: Tried 1 solutions.

Writing lock file

Finding the necessary packages for the current system

Package operations: 0 installs, 1 update, 0 removals

  • Updating python-dotenv (0.17.0 -> 0.17.1): Downloading... 100%
  • Updating python-dotenv (0.17.0 -> 0.17.1): Installing...
  • Updating python-dotenv (0.17.0 -> 0.17.1)
```

Perhaps you could tell us more about your environment?

**Comment by jasonk-specialized** [comment]
I'll check again and see what other packages I have in my poetry config. Perhaps its a combination of packages that is causing it to hang for me.

**Comment by jasonk-specialized** [comment]
Steps to reproduce.

Perhaps I'll chime this problem into the poetry project instead. I'm guessing something else is going on with how they are resolving dependencies here.

```shell
poetry init
poetry add cryptography
poetry add python-dotenv
```
