### ISSUE TITLE
load_dotenv() returns True even if .env file is not found

### ISSUE THREAD

**Issue by scollovati** [theskumar/python-dotenv#321]
This behaviour is not ideal since if the configuration file is not found in the filesystem it may be better to return False.
In this way the user can write something like:
```python
if load_dotenv():
    #do stuff
else
    print("No file .env found")
```

# Steps to reproduce
```
In [1]: import dotenv

In [2]: dotenv.load_dotenv()
Out[2]: True

In [3]: dotenv.find_dotenv()
Out[3]: ''
```

**Comment by theskumar** [comment]
I understand the return response for `load_dotenv` is not ideal, but at the same time as `load_dotenv` just not accepts a file on the filesystem but a StringIO as well, so the return value indicating the existing of a file doesn't make any sense. 

There are other ways to get around this for you use case.

1. Enable `verbose=True` in load_dotenv to get a error log if file is not found.
2. Use the `find_dotenv` function to check if the file exist or not or simply check the file yourself, before loading the values from .env.

It feel like exposing an instance of `Dotenv` class might make sense here or `None` if nothing is processed by load_dotenv. cc: @bbc2 thoughts?

**Comment by bbc2** [comment]
> so the return value indicating the existing of a file doesn't make any sense.

I think it would be OK to return `True` if a `StringIO` was provided.   `False` would still be useful for users using files.

So I'd suggest implementing that, or changing strategies and adding a `raise_if_file_not_found` argument to `load_dotenv` and `dotenv_values`.  One or the other, but not both.

> It feel like exposing an instance of Dotenv class might make sense here or None if nothing is processed by load_dotenv. 

Although it could lead to interesting features, I'm worried that exposing the `Dotenv` class would increase our API surface considerably.  I kind of like the fact that we can change that class easily at the moment, which wouldn't be the case if we exposed it to users.

About returning `None`, what would be the advantage compared to returning `False`?

**Comment by iamsannyrai** [comment]
@theskumar why we can access values from .env files by just os.getenv("VARIABLE_NAME") without even calling load_env() ? Any reason?

**Comment by ProfessorPiggos** [comment]
> @theskumar why we can access values from .env files by just os.getenv("VARIABLE_NAME") without even calling load_env() ? Any reason?

load_env sets the environment variables of the python instance to the ones found in the file. If you don't call I, then it uses the local variables of the system.

**Comment by larsks** [comment]
I've submitted a PR that changes the behavior of `dotenv.Dotenv.set_as_environment_variables` such that `load_dotenv` will return `False` if it is unable to load any environment variables from a file or stream. I think that addresses the concerns raised in this issue.

**Comment by rptaylor** [comment]
I think this is the same or similar to https://github.com/theskumar/python-dotenv/issues/297  ?

**Comment by cbarkinozer** [comment]
I changed a value in my .env but kept receiving the previous value (I saved the .env file after changing it). I tried deleting the __pycache__ but it did not work. When I closed the vs code terminal and opened a new one it was resolved. There is a cache but I could not understand where and why.
