### ISSUE TITLE
.env file can not be config with bash output 

### ISSUE THREAD

**Issue by Wsine** [theskumar/python-dotenv#322]
I tried with the below .env file that CUDA_VISIBLE_DEVICES can not be set automatically.

```sh
# .env
CUDA_VISIBLE_DEVICES=$(nvidia-smi --query-gpu=memory.free --format=csv,nounits,noheader | nl -v 0 | sort -nrk 2 | cut -f1 | head -n1 | xargs)
```

is it that possible to support this feature? or this is out of the design?

**Comment by theskumar** [comment]
This library is designed to provide this kind of functionality. More discussion here: https://github.com/theskumar/python-dotenv/issues/402
