### ISSUE TITLE
.env is actually an extension

### ISSUE THREAD

**Issue by JJ** [theskumar/python-dotenv#323]
Which means that dotenv files should probably be called whatever.env, *not* .env.whatever. In general, looks like the convention for dotfiles is to consider the name an extension (as in .dockerignore, or .gitignore...)

**Comment by willharris** [comment]
The idea that dot-files would be "extensions" seems is a particularly DOS/Windows view of the world. dot-files have a long history in the Unix world, and are meant to be hidden from a normal `ls` directory listing. See e.g. https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory

**Comment by hartwork** [comment]
The [dotenv equivalent of the the Ruby world](https://github.com/bkeepers/dotenv) has these cases in [their Readme](https://github.com/bkeepers/dotenv#dotenv--):
- `Dotenv.load('file1.env', 'file2.env')`
- `Dotenv.parse(".env.local", ".env")`
- [`.env{.{development,production,test}{.local,}}`](https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use)

So both `.env.foo` and `foo.env` seem to be common patterns. If that's true, maybe there is no bug to fix here?

**Comment by bbc2** [comment]
I didn't know the `file.env` convention existed, so I learned something here.

Regardless, `.env.local` and other are indeed quite common.  See [Docker Compose's documentation](https://docs.docker.com/compose/environment-variables/#using-the---env-file--option) for example:

> By passing the file as an argument, you can store it anywhere and name it appropriately, for example, .env.ci, .env.dev, .env.prod.

So, it's an interesting topic, but I don't think there's an issue with our readme and will thus close this issue and the related PR.
