### ISSUE TITLE
Incorrect interpolation for default values

### ISSUE THREAD

**Issue by skozlovf** [theskumar/python-dotenv#326]
`python-dotenv` docs says:
> Python-dotenv can interpolate variables using POSIX variable expansion.

This case doesn't work in python-dotenv `0.17.0`:

`.env` file:
```
ENV=dev
NAME=cluster
FULL_NAME=${FULL_NAME:-${NAME}-${ENV}}
```

```
$ dotenv -- run python -c 'import os; print(os.environ["FULL_NAME"])'
${NAME-dev}
```

Correct behavior:

`1.sh` file:
```
#!/usr/bin/env bash
. .env
echo ${FULL_NAME}
```

```
# ./1.sh
cluster-dev
```

Simpler case doesn't work either: `FULL_NAME=${FULL_NAME:-${NAME}}` -> `${NAME}`.

See ` Parameter Expansion` section here: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05

**Comment by skozlovf** [comment]
One more thing:
```
FULL_ENV_NAME=${FULL_ENV_NAME:-"{{ xx }}"}
```

generates:
```
"{{ xx }"}
```

**Comment by theskumar** [comment]
This library is designed to provide this kind of functionality. More discussion here: https://github.com/theskumar/python-dotenv/issues/402
