### ISSUE TITLE
Changing env file during after loading does not allow update of env variables

### ISSUE THREAD

**Issue by yeeshue99** [theskumar/python-dotenv#331]
env file
```
GAS="20000"
```
Loading env
```python
from pathlib import Path

BASE_DIR = Path(".")
ENV_DIR = BASE_DIR / "env"
DOT_ENV = ENV_DIR / ".env"

load_dotenv(DOT_ENV)
GAS_AMOUNT = int(os.getenv("MINT_GAS_AMOUNT"))
```

If you then change the file, say to this:
env file
```
GAS="50000"
```

None of these methods get a new variable based on the file contents.
```python
load_dotenv(DOT_ENV)
GAS_AMOUNT = int(os.getenv("MINT_GAS_AMOUNT"))
```

```python
del GAS_AMOUNT
load_dotenv(DOT_ENV)
GAS_AMOUNT = int(os.getenv("MINT_GAS_AMOUNT"))
```

You can't do load_dotenv, since it won't update, and you also can't delete the variable, as that won't work either. You have to start up a whole new shell.

**Comment by bbc2** [comment]
Python-dotenv doesn't update environment variables which are already set by default.  Perhaps you could try `load_dotenv(DOT_ENV, override=True)`?  Or else, something like `del os.environ["MINT_GAS_AMOUNT"]` but I don't know if that's a good idea.

**Comment by yeeshue99** [comment]
override = True, seemed to work. Was unaware of the option. Thank you!

**Comment by tljstewart** [comment]
So strange, this should be the default behavior, as in exactly what `load_dotenv()` implies...

**Comment by jyotirmay123** [comment]
> So strange, this should be the default behavior, as in exactly what `load_dotenv()` implies...

Should be the default .. +1

**Comment by agardnerIT** [comment]
Changing values at runtime fits better with feature flags. For an open source solution, check https://flagd.dev
