### ISSUE TITLE
Can you use a more well-known license, e.g. Apache ? 

### ISSUE THREAD

**Issue by qiulang** [theskumar/python-dotenv#333]
Hi I was wondering can you use a more well-known license, e.g. Apache ? 
I read your license file "Redistributions of source code must retain the above copyright notice,  this list of conditions and the following disclaimer..." I feel Apache license covers that (I could be wrong of course).

Currently, without a clear license model my employer forbids me using it in our close-source projects.

Thanks a lot.

Qiulang

**Comment by bbc2** [comment]
I'm bad with licensing stuff but I think we are simply using BSD-3 here: https://opensource.org/licenses/BSD-3-Clause.  I don't know if that's the best license we could use but at least it's rather common.
