### ISSUE TITLE
Git HEAD: setup.cfg should use "description_file" instead of "description-file" to address warnings

### ISSUE THREAD

**Issue by hartwork** [theskumar/python-dotenv#334]
Hi!

setuptools 54.1.0 started warning about the use of dash-based key `description-file` in section `metadata` …

> Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead

… at … https://github.com/theskumar/python-dotenv/blob/303423864ae00f8d5f21cb39d6421a7d775a3daf/setup.cfg#L20

The related upstream commit is https://github.com/pypa/setuptools/commit/a2e9ae4cb and here's an example of how another project has been addressing the same issue, for comparison: https://git.meb.uni-bonn.de/puppet/puppet-oslo/commit/086a3b68052d6a2d574f9ba56b54963fcfe75652

Thanks and best, Sebastian

PS: This issues has been brought to my attention by downstream bug report https://bugs.gentoo.org/796404 in Gentoo.

**Comment by bbc2** [comment]
Thanks!

**Comment by hartwork** [comment]
Cool, thank you!
