### ISSUE TITLE
cannot parse with semicolons

### ISSUE THREAD

**Issue by eangius** [theskumar/python-dotenv#343]
Semicolons ``;`` are valid syntax in `.env` files but they do not parse when loading with this library. Rather than requiring semicolons to be removed in the config file, would like this library to handle them when present. Below is an example use-case.

-----------------------
**production.env**
```text
DB_HOST='localhost'; DB_PORT=1234;
DB_NAME='mydatabase';
```

**source code**
```python
from dotenv import dotenv_values
cfg = dotenv_values("/path/to/production.env")
```

**error**
```
Python-dotenv could not parse statement starting at line 1
Python-dotenv could not parse statement starting at line 2
```

**Comment by theskumar** [comment]
@eangius Thanks for reporting, but unless we have more similar request and community in support this logic, I'll have to put this request as out of scope for this library.
