### ISSUE TITLE
No `.env` but get Python-dotenv could not parse statement starting at line

### ISSUE THREAD

**Issue by abcfy2** [theskumar/python-dotenv#364]
I have no `.env` in my working project, but I get this output:

```
Python-dotenv could not parse statement starting at line 20
Python-dotenv could not parse statement starting at line 22
Python-dotenv could not parse statement starting at line 23
Python-dotenv could not parse statement starting at line 24
```

```sh
$ ls -a
.  ..  dist  export_equipment_raw_data.egg-info  .git  .gitignore  main.py  pyenv  pyproject.toml  REAMDE.md  setup.cfg
```

What's wrong ?

**Comment by theskumar** [comment]
Are you sure you have no .env file in the parent directories as well?

**Comment by abcfy2** [comment]
Thanks you, I find there is `.env` in my home directory. I don't think it's a good idea to search parent directory. Is there any way to disable this feature?

**Comment by theskumar** [comment]
If you provide the path to the ".env" file explicitly, it will not do the lookup in parent directories.

**Comment by abcfy2** [comment]
Got it.
