### ISSUE TITLE
Support for passing ```dict``` or ```json``` as parameters to ```load_dotenv``` method

### ISSUE THREAD

**Issue by mesajidiqbal** [theskumar/python-dotenv#369]
It's common nowadays to keep some environment variables in a json file (e.g. ```env_settings.json```) or encrypt environment variables values in env files (my use case), So it would be nice to add ```dict``` and ```json``` as parameters in ```load_dotenv``` method.
e.g: 
1.   ```load_dotenv(dict=env_dict)```  # where env_dict was generated using ```dotenv_values()``` method and then doing some processing
2.   ```load_dotenv(json=json_string)```  # where json_string is json.dumps(env_dict)

My use case:
- The values are RSA encrypted and need to be decrypted before getting loaded as environment variables

My approach:
- loaded the env file as env_dict using ```dotenv_values``` method
- decrypted the values in place in env_dict

Now I am setting the environment variables values manually, but it would have been nice if I would have been able to pass that dict to ```load_dotenv``` method

**Comment by theskumar** [comment]
I'm afraid this will be out of scope for this project. There is numerous formats that will need to be supported. 

That said, if there is really a use case for it, these can exist as separate project and i would be happy to link it here as related projects.

**Comment by mesajidiqbal** [comment]
Sure, will provide details of the project, if I find any or start my own.
Just wanted to highlight it because I found that only exposing the ```set_as_environment_variables``` method of ```DotEnv``` class as an API would fulfill many of similar use cases.

Anyway, thanks a lot for this interesting project :blush:.

**Comment by posita** [comment]
The setting of environment variables [isn't too onerous](https://github.com/theskumar/python-dotenv/blob/ba9408c5048e8e512318df423541d2b44ac6019f/src/dotenv/main.py#L86-L96) if you want to replicate it. You might be able to do what you need with something like:

``` python
import os
def update_environment_variables(env: dict[str, str | None], override: bool):
    for k, v in env.items():
        if k in os.environ and not override:
            continue
        if v is not None:
            os.environ[k] = v
        elif k in os.environ:  # I added this branch
            del os.environ[k]  # or os.environ[k] = None or whatever
```

Then you can do:

``` python
import json
from collections.abc import Mapping
json_value = json.load(path)
assert isinstance(json_value, Mapping)  # may want to further verify that you actually have a dict[str, str | None]
update_environment_variables(json_value)
```

I guess if there's anything this project might do, it might be to tease out a generalized implementation (maybe a `classmethod` on `DotEnv`) for updating the environment given a `dict[str, str | None]`?

**Comment by theskumar** [comment]
Like @posita mentioned updating an existing env is very trivial using python and you would be better off not using a library for this.
