### ISSUE TITLE
[Question] Setting .env absolute path to a variable in .env

### ISSUE THREAD

**Issue by atakanokan** [theskumar/python-dotenv#377]
I am trying to set an environment variable called `PROJECT_ROOT_PATH` (= absolute path of the .env file directory) and use that as the root directory to add relative directory paths within python scripts. However, I couldn't find a way to do this in the .env file dynamically. 

Python way:
```
from pathlib import Path
PROJECT_ROOT_DIR = Path(__file__).parent.resolve()
```

**Comment by joaoe** [comment]
In Bash $BASH_SOURCE gives you the path to the running script, relative or absolute depending how it was called (similar to argv[0]), e.g.:
```
$ bash script.sh -> $BASH_SOURCE = script.sh
$ bash /path/script.sh -> $BASH_SOURCE = /path/script.sh
```
this can be used to know the folder where it is located
```
# in .env
SCRIPTFOLDER="$(dirname "$(readlink -m "$BASH_SOURCE")")
```
However, dotenv is not a bash emulator and can't run bash commands or variable substitutions.
So for your use case, you just have to hardcode the full path.
