### ISSUE TITLE
bug: Getting "dotenv" could not be resolved error

### ISSUE THREAD

**Issue by Pradumnasaraf** [theskumar/python-dotenv#380]
- Getting **`Import "dotenv" could not be resolved Pylance (reportMissingImports)`**  again and again, although it is not affecting in development and running of the program, sometimes it can be annoying.

![Screenshot from 2022-03-01 14-50-33](https://user-images.githubusercontent.com/51878265/156141228-c053d692-2dab-4b45-9295-e9c5c201f4a8.png)

**Comment by bbc2** [comment]
Hi, thanks for reporting this issue.  We've seen similar reports in the past but so far I don't think any of them has ever shown that Python-dotenv itself was the cause of the issue.  Do you have any reason to believe this is something we can fix in Python-dotenv?

**Comment by thatguylor** [comment]
Hi there, i just faced the exact same issue as you, what helped me was to include 
`# .env ` at the header of your .env file, i realized at least that VScode was able to recognize the dotenv namespace. And the import error should be gone.

**Comment by diegotco** [comment]
Same issue here :(

**Comment by SeverumYu** [comment]
Same

**Comment by Cliciaf** [comment]
Consegui resolver com: sudo pip3 install python-dotenv

**Comment by BraveVN** [comment]
> Consegui resolver com: sudo pip3 install python-dotenv

I'm on Windows 10, CMD runs as Admin didn't work

**Comment by wnowicki** [comment]
Same here. It's definitely installed in venv and even the system.

**Comment by jacksonpradolima** [comment]
Same issue

**Comment by Rishat-Ver** [comment]
Тщже самое

**Comment by jrledezma** [comment]
same here

**Comment by BraveVN** [comment]
For those who come to this topic, I figured out that I need to setup a virtual environment (It's a basic for Python, I'm a Nodejs-based so I don't know anything about virtual env). You can see the instruction here: [https://docs.python.org/3/library/venv.html](https://docs.python.org/3/library/venv.html). 

Then put all of your codebase into that new venv folder → activate the virtual env → install packages and it works.

Make sure to activate the virtual env every time you install package and run the code.

**Comment by boluocat** [comment]
same here

**Comment by kayceenuel** [comment]
Who has solved this problem? Because I am currently facing the same issue.

**Comment by kayceenuel** [comment]
# I just solved it now. 

##Open the command palette 

Type and select Python: Select Interpreter.
Choose the interpreter located in your virtual environment (it should show a path like myproject/myVenv/bin/python or myproject\myVenv\Scripts\python.exe).

**Comment by welingtonsanttos** [comment]
1. $ python -m venv venv

2. $ source ./venv/Scripts/activate

3. $ pip install python-dotenv
