### ISSUE TITLE
Quote treatment

### ISSUE THREAD

**Issue by hy144328** [theskumar/python-dotenv#381]
While I consider `.env` files useful for debugging, I will also use them to deploy secrets to my production environment.
For example:

```
kubectl create secret generic my-secret --from-env-file=.env
```

Now comes my problem:
What standard do the `.env` files in `python-dotenv` follow?
This is relevant when `.env` files are parsed by other programs.
For example:

*   `python-dotenv` drops quotes from environment variables.
*   `kubectl` leaves quotes as part of the string.

This is also difficult to debug because you do not want to print secret environment variables to the console or log them.
It would be nice to (i) have your own specification, (ii) cite a reference specification, or (iii) outline pitfalls for dummies like myself.
What do you think?

**Comment by hy144328** [comment]
PS:
Big fan of `dotenv-python`.
Use it in literally every project. :-)

**Comment by bbc2** [comment]
Unfortunately, I don't know of any standard with regards to the format of `.env` files.

We also don't have a formal specification for Python-dotenv.  The closest we have to such a specification is https://github.com/theskumar/python-dotenv#file-format.

Two years ago we fixed a few inconsistencies in the format expected by Python-dotenv.  To help with that effort, I compared several different parsers: https://bbc2.github.io/dotenv-parser-comparisons/.  As you can see, there seems to be a consensus about double-quotes: they are removed by all the parsers I tested.  However, each parser is different for some aspects (escaping, single quotes, variables, etc).

I didn't know of `kubectl`'s expectations so thank you for bringing that up.  We probably won't take it into account right away but I always like to know what other pieces of software do. I wonder if it's the same format is expected by the rewrite of Docker Compose in Go (the former version, in Python, used Python-dotenv).

I'm glad you like Python-dotenv :)
