### ISSUE TITLE
Wheel should no long be "universal" after Python 2.7 dropped

### ISSUE THREAD

**Issue by YKdvd** [theskumar/python-dotenv#383]
The last version which supported Python 2.7 was apparently 0.18.0.  "setup.py" seems to have changed appropriately to https://github.com/theskumar/python-dotenv/blob/ba9408c5048e8e512318df423541d2b44ac6019f/setup.py#L35
which keeps pip from installing anything new than 0.18.0 via PiPi.  
But if you look at the [PyPi download page](https://pypi.org/project/python-dotenv/#files), you see this:
> Built Distribution
> [python_dotenv-0.19.2-py2.py3-none-any.whl ]
> Uploaded Nov 11, 2021 py2 py3

where the wheel is falsely advertising "py2" compatibility.  I think you need to remove this from "setup.cfg" [bdist] section
https://github.com/theskumar/python-dotenv/blob/ba9408c5048e8e512318df423541d2b44ac6019f/setup.cfg#L10
so that you don't build a universal wheel anymore.

**Comment by theskumar** [comment]
Thanks @YKdvd for reporting. I'll look into this and update.
