### ISSUE TITLE
Feature: Throw error if example environment variables aren't set in the environment

### ISSUE THREAD

**Issue by keshavkaul** [theskumar/python-dotenv#39]
I have come across a node dotenv implementation that does this:
https://github.com/rolodato/dotenv-safe.

I think this will enable early detection of missing environment variables.

**Comment by hugochinchilla** [comment]
I like the idea, but not using a .env.example with empty vars, a .env.example or .env.sample should be a ready to go file with sane defaults, at least is what I try to do with them.

For PHP development I use `vlucas/phpdotenv` it implements this feature like this:

```

**Comment by hugochinchilla** [comment]
I like the idea of having mandatory variables, but I don't like using a .env.example (or .env.sample) like that.
I try to make them a ready to use example, not a simple enumeration of empty variables.

When working on PHP projects I use `vlucas/phpdotenv` and it implements the idea this way:

```php
<?php
// directory to look for an .env file
$dotenv = new Dotenv\Dotenv(__DIR__);
// load .env file (overloading existing variables)
$dotenv->overload();
// make some variables mandatory, trows error if not present
$dotenv->required(['DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS']); 
```

I would suggest to implement like this for python-dotenv:

```python
dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path, required=('DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS'))
```

But this can be already achieved by using `python-dotenv` with `python-decouple`, which I always use together, `python-dotenv` takes care of loading `.env` files, and `python-decouple` for reading the env and aplying castings or validations.

**Comment by keshavkaul** [comment]
>I try to make them a ready to use example, not a simple enumeration of empty variables.

We can use comments that define the variable usage. Its always a good thing to let other team members consciously modify their own .env file based on the sample instead of simply copying from the sample.

>But this can be already achieved by using python-dotenv with python-decouple

Hmm interesting..after reading python-decouple docs, it seems to do the same things as python-dotenv with a bit more features such as default if not found, casting to a type.

**Comment by keshavkaul** [comment]
I think python-decouple will throw an error only if we try to fetch a missing variable not when the server/app bootstraps

Providing required variables as a tuple list won't scale if we have many required variables.
>load_dotenv(dotenv_path, required=('DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS'))

**Comment by theskumar** [comment]
Hi Guys, while I think it's a nice to have feature in an application. But I don't agree that it should be solved through this library.

The library is responsible for only populating the system's environment variable with what is available in .env. It would be responsibility of code responsible for consuming those environment variable to handle the missing variables.

In my case, i use django-environ to read the environment variable and it sort of handles missing variables pretty nice.

**Comment by AlJohri** [comment]
I use this for checking environment variables: https://github.com/humangeo/preflyt
