### ISSUE TITLE
how to set the .env file in the terminal?

### ISSUE THREAD

**Issue by chanansh** [theskumar/python-dotenv#391]
how can I export the settings to the current terminal environment variables?
e.g. `dotenv load` or something like that.

**Comment by chanansh** [comment]
In fish terminal: `export  (cat .env |xargs -L 1)`
see https://stackoverflow.com/questions/25632846/how-to-set-environment-variables-in-fish-shell

in bash see 
https://unix.stackexchange.com/questions/79064/how-to-export-variables-from-a-file

**Comment by theskumar** [comment]
Using a shell command as you suggested is your best bet with what you are looking for. You can create a shell alias.

- https://gist.github.com/mihow/9c7f559807069a03e302605691f85572
- https://stackoverflow.com/a/716046
