### ISSUE TITLE
Adding support for invoking cli as `python -m dotenv`

### ISSUE THREAD

**Issue by bialix** [theskumar/python-dotenv#394]
I'm heavily using virtualenv as many python developers today. And I don't use "activate" in my workspaces, but instead run just fine local symlink (or batch file on Windows) to execute something in current venv workspace. That works just fine as far as every lib I care about has the way to run it with `python -m`.

Please consider adding this little addition to your library that allows running your utility as `python -m dotenv`.

**Comment by bialix** [comment]
You need to put the following chunk of code to your `src/dotenv/__main__.py` file:

```
from .cli import cli

if __name__ == "__main__":
    cli()
```

**Comment by theskumar** [comment]
This sounds great! I'll get it added. 

Thank you
