### ISSUE TITLE
--format= option for CLI list command

### ISSUE THREAD

**Issue by sammck** [theskumar/python-dotenv#405]
It would be nice to have a way to dump all variables as JSON, which can be used by many other tools. I'd propose addition of a --json or -j option on the "list" command.

I'd be happy to submit a pull request if it sounds interesting.

**Comment by sammck** [comment]
sorry i missed your format= suggestion; I will revice and resubmit

**Comment by sammck** [comment]
I was inspired by your idea to allow more formats with "--format=", and I added two more formats, "shell" and "export".  These formats can be directly executed by a posix shell, as in:

```bash
eval "$(dotenv list --format=shell)"
```

**Comment by theskumar** [comment]
Nice I'll review it over the weekend!
