### ISSUE TITLE
Error Handling in rewrite is incorrect.

### ISSUE THREAD

**Issue by theGOTOguy** [theskumar/python-dotenv#413]
Look at:
https://github.com/theskumar/python-dotenv/blob/master/src/dotenv/main.py#L136

If lines 136, 137 or 140 there are ever hit, an error "local variable 'dest' referenced before assignment" will be thrown, because the `dest` variable only exists within the scope of the `with` block above.

**Comment by theGOTOguy** [comment]
Resolved by https://github.com/theskumar/python-dotenv/pull/414

**Comment by theskumar** [comment]
I had to revert #414 because the test was failing. Do you want to take another stab at it?

**Comment by theGOTOguy** [comment]
Looks like it was just a linter error.  I submitted a new PR -- #423 should work.
