### ISSUE TITLE
Python 3.10 Error when debugging

### ISSUE THREAD

**Issue by dillonco** [theskumar/python-dotenv#421]
I'm seeing this error when debugging a function using Python 3.10. Using the latest python-dotenv.

```    
from dotenv import load_dotenv
/home/.local/share/virtualenvs/WsmUZ7f/lib/python3.10/site-packages/dotenv/__init__.py:3: in <module>
    from .main import (dotenv_values, find_dotenv, get_key, load_dotenv, set_key,
/home/.local/share/virtualenvs/WsmUZ7f/lib/python3.10/site-packages/dotenv/main.py:12: in <module>
    from .parser import Binding, parse_stream
/home/.local/share/virtualenvs/WsmUZ7f/lib/python3.10/site-packages/dotenv/parser.py:28: in <module>
    Original = NamedTuple(
/usr/lib/python3.10/typing.py:2323: in NamedTuple
    return _make_nmtuple(typename, fields, module=module)
/usr/lib/python3.10/typing.py:2250: in _make_nmtuple
    nm_tpl = collections.namedtuple(name, fields,
/usr/lib/python3.10/collections/__init__.py:393: in namedtuple
    field_defaults = dict(reversed(list(zip(reversed(field_names),
E   TypeError: 'dict' object is not callable
```

Removing python-dotenv also fixes the problem. I also saw a similar issue with https://pypi.org/project/google-cloud-logging/ so I doubt it's related to this library specifically, but maybe a dependency?

**Comment by theskumar** [comment]
@dillonco please share how you are using the dotenv library in your codebase. The issue seems you are trying to access the dict with curly brackets, i.e., `("key1")` and not using square brackets i.e. `["key1"]`

**Comment by dillonco** [comment]
Apologies this is unrelated to your library. It has something to do with my python installation, but I'm still unsure why it was breaking.
