### ISSUE TITLE
path ...\v2 turns to ...\x0b2

### ISSUE THREAD

**Issue by TiDiCom** [theskumar/python-dotenv#429]
I have an .env file which has something like:
PYTHONPATH="C:\Users\xyz\v2"

If I run the python file:
```
from dotenv import dotenv_values
config = dotenv_values(".env")
print(config)
```

it gives me:
`OrderedDict([('PYTHONPATH', 'C:\\Users\\xyz\x0b2')])`
instead of expected:
`OrderedDict([('PYTHONPATH', 'C:\\Users\\xyz\\v2')])`

If I instead have a big V2 it works as expected. It seems a small v2 (version 2) in the path name seems to create some issues.

**Comment by bbc2** [comment]
The escape `\v` is for the special character "vertical tab" (see https://en.wikipedia.org/wiki/ASCII#Control_code_chart). The list of supported escapes for double-quoted values is provided at https://github.com/theskumar/python-dotenv#file-format.

For your case, with Windows paths, I would suggest using single quotes (e.g. `PYTHONPATH='C:\Users\xyz\v2'`). Would that work for you?

**Comment by theskumar** [comment]
@TiDiCom I hope answer by bbc2 helped you. If you still facing issues, feel free to re-open the issue.
