### ISSUE TITLE
dotenv run is overriding existing environment variables

### ISSUE THREAD

**Issue by sourcedelica** [theskumar/python-dotenv#444]
From the README: 
> By default, `load_dotenv` doesn't override existing environment variables.

The contents of `.env`:
```
FOO=BAZ
```
Example:
```
$ dotenv --version
dotenv, version 0.21.0

$ printenv FOO
BAR

$ dotenv run printenv FOO
BAZ
```

Is this expected?  Thanks

**Comment by sourcedelica** [comment]
I found the issue:
```
@click.option(
    "--override/--no-override",
    default=True,
    help="Override variables from the environment file with those from the .env file.",
)
```
Is that correct?

**Comment by sourcedelica** [comment]
It looks like it's consistent with `dotenv_values()` so it seems intentional. 

> With load_dotenv(override=True) or dotenv_values(), the value of a variable is the first of the values defined in the following list:
>
>    Value of that variable in the .env file.
>    Value of that variable in the environment.

**Comment by theskumar** [comment]
Hi @sourcedelica, it's intensional and the reason for the `load_dotenv` not doing it by default is because of the legacy reasons.
