### ISSUE TITLE
Use PEP 541 to take over deprecated and abandoned `dotenv` package

### ISSUE THREAD

**Issue by zmievsa** [theskumar/python-dotenv#448]
`dotenv` package has been abandoned for many years now. I propose to use PEP 541 to take over that package name and make it an alias to this package. I have seen countless cases of people trying to install dotenv instead of python-dotenv, failing and resorting to google.

The request can be opened here: https://github.com/pypi/support/issues
Here's an example of a request: https://github.com/pypi/support/issues/2218

**Comment by Ovsyanka83** [comment]
Note that if anyone makes this request, it must be the the maintainer(s) of python-dotenv.

**Comment by theskumar** [comment]
Thanks, @Ovsyanka83, for the resources and guidance. It's the right time to do it. 

Referencing here a related issue with name conflict but at the os level, and would probably need a different resolution.  

- https://github.com/theskumar/python-dotenv/issues/339

**Comment by stuaxo** [comment]
+1 for this, I've wasted hours on this myself in the past.

**Comment by 1a2a34v** [comment]
+1

**Comment by zmievsa** [comment]
Now followed here:
https://github.com/pypi/support/issues/2568
