### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1065: ordinal not in range(128)

### ISSUE THREAD

**Issue by patvdleer** [theskumar/python-dotenv#45]
On setup:

P3.4
~~~
Collecting python-dotenv (from -r requirements.txt (line 4))
  Downloading python-dotenv-0.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-v231dm4e/python-dotenv/setup.py", line 5, in <module>
        readme = readme_file.read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1065: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v231dm4e/python-dotenv/
~~~

P3.5
~~~
Collecting python-dotenv (from -r requirements.txt (line 4))
  Downloading python-dotenv-0.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s94tagti/python-dotenv/setup.py", line 5, in <module>
        readme = readme_file.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1065: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s94tagti/python-dotenv/
~~~

**Comment by theskumar** [comment]
@patvdleer i tried quickly on my mac using Python 3.5.2 and it seems install just fine. I'm going try it on a fresh machine. Are you able to provide the little info about your machine.

**Comment by patvdleer** [comment]
I tested this in docker images, both [Ubuntu official images](https://hub.docker.com/_/ubuntu/), 14.04.5 and 16.04. 

```
- apt-get update && apt-get install -y python3 python3-dev firefox xvfb curl build-essential libssl-dev libffi-dev
- echo "" > .env
- export PATH=$PATH:`pwd`/drivers/x64
- curl -sS https://bootstrap.pypa.io/get-pip.py | python3
- pip3 install -r requirements.txt
- pip3 install -r requirements-dev.txt
```

**Comment by chananshgong** [comment]
I have the same issue with a Windows machine.

> C:\WINDOWS\system32>pip install python-dotenv
> Collecting python-dotenv
>   Using cached python-dotenv-0.6.2.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\HANAN~1.SHT\AppData\Local\Temp\pip-build-hde9g_in\python-dotenv\setup.py", line 5, in <module>
>         readme = readme_file.read()
>       File "c:\users\hanan.shteingart\anaconda3\lib\encodings\cp1255.py", line 23, in decode
>         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>     UnicodeDecodeError: 'charmap' codec can't decode byte 0x9c in position 1067: character maps to <undefined>
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\HANAN~1.SHT\AppData\Local\Temp\pip-build-hde9g_in\python-dotenv\

**Comment by fengsi** [comment]
Python 3.6 (FreeBSD 11-RELEASE in Vagrant):
```
Collecting python-dotenv
  Downloading python-dotenv-0.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cha37wge/python-dotenv/setup.py", line 5, in <module>
        readme = readme_file.read()
      File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1065: ordinal not in range(128)
```

**Comment by fengsi** [comment]
@theskumar verified that on Mac, installation worked with Python 3.6.0.

Mac is usually case-insensitive while other *nix is not; not sure if that could be related to this behavior (I've had similar issues with Node in the past)?

**Comment by theskumar** [comment]
While I look into the unicode mess, i'm going to make a new release without the `readme_file.read()` in the setup.py.

**Comment by theskumar** [comment]
python-dotenv 0.6.3 released. @patvdleer @fengsi @chananshgong please check if it works for you guys.

**Comment by fengsi** [comment]
@theskumar it works for now.  Thanks.

**Comment by benjaminweb** [comment]
Note: `export LC_ALL=de_DE.UTF8` did the job for me having the same symptom with a different package.
