### ISSUE TITLE
charmap error on pip install in Windows

### ISSUE THREAD

**Issue by chananshgong** [theskumar/python-dotenv#46]
> pip install -U python-dotenv
> Collecting python-dotenv
>   Using cached python-dotenv-0.6.2.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\...\AppData\Local\Temp\pip-build-q6z2d_sj\python-dotenv\setup.py", line 5, in <module>
>         readme = readme_file.read()
>       File "c:\users\hanan.shteingart\anaconda3\lib\encodings\cp1255.py", line 23, in decode
>         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>     UnicodeDecodeError: 'charmap' codec can't decode byte 0x9c in position 1067: character maps to <undefined>
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\...\AppData\Local\Temp\pip-build-q6z2d_sj\python-dotenv\

**Comment by theskumar** [comment]
@chananshgong please let me know if you are still getting issues with v0.6.3, after handling the exception.
