### ISSUE TITLE
 No module named 'dotenv'

### ISSUE THREAD

**Issue by devyani08** [theskumar/python-dotenv#463]
I encountered an issue with the dotenv module where an ImportError: No module named 'dotenv' error occurs when attempting to import the module in my Python script.
After running "python -m autogpt" command i am encountering this error. I expected to be able to import and use the dotenv module without encountering any issues.

```python
import os
import random
import sys

from dotenv import load_dotenv

if "pytest" in sys.argv or "pytest" in sys.modules or os.getenv("CI"):
    print("Setting random seed to 42")
    random.seed(42)

# Load the users .env file into environment variables
load_dotenv(verbose=True, override=True)

del load_dotenv

``` 
When attempting to import the dotenv module, I received an ImportError indicating that the module could not be found.

Environment:

Python version: 3.10.5
Operating System: Windows 11
Additional Information:
I confirmed the installation of the dotenv module by running the command pip show dotenv, which displayed the module details. Despite this, I am still unable to import it in my script. Ii try to uninstall the dotenv module and reinstall the module still could not find the solution.

![Screenshot 2023-06-08 143851](https://github.com/theskumar/python-dotenv/assets/85363960/c6f9d695-329a-424c-9113-77b23db4840b)
 Your assistance in resolving this matter is greatly appreciated.

**Comment by mak448a** [comment]
Did you install it with `pip install python-dotenv`?

**Comment by devyani08** [comment]
Yes, and when it did not worked i uninstall the dotenv module and
reinstalled it, still finding difficulty in setting up AutoGPT.

**Comment by theskumar** [comment]
@devyani08 what's is the out of your `pip freeze | grep "dotenv"`

Do you believe installing AutoGPT corrupted your setup?

**Comment by devyani08** [comment]
Have used `pip freeze | findstr "dotenv"` instead of `pip freeze | grep "dotenv"`  and the output was `dotenv==0.0.5
python-dotenv==1.0.0`

It might be a possibility that AutoGPT has corrupted my setup!

**Comment by theskumar** [comment]
@devyani08 The issue is you have both `dotenv` and `python-dotenv` as dependency in your python environment. 

autogpt use [this](https://github.com/Significant-Gravitas/Auto-GPT/blob/master/requirements.txt#L6) library and not the `dotenv==0.0.5`

You can try uninstalling the `dotenv` and see if your issue is resolved. 

```
pip uninstall dotenv
```

**Comment by theskumar** [comment]
Strange, did you try reaching out the maintainers of AutoGPT? 

FWIW, I couldn't identify anything we need to fix in this library.

**Comment by thorrak** [comment]
I had this happen myself today. What I needed to do to fix it was:

1. Uninstall `dotenv`
2. Uninstall `python-dotenv` 
3. Reinstall `python-dotenv`

Simply uninstalling `dotenv` wasn't sufficient to solve the problem.

**Comment by devyani08** [comment]
Already tried this, i am installing python 3.9 to check whether the problem is with python 3.10 or installed packages.

**Comment by arligan** [comment]
> Already tried this, i am installing python 3.9 to check whether the problem is with python 3.10 or installed packages.

Any progress?

**Comment by Finn10111** [comment]
I think I cannot contribute anything useful but I have the same problem with Python 3.11 within a virtualenv. I think I have installed the correct module:

```
$ pip freeze | grep dotenv
python-dotenv==1.0.0
```

```
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

**Comment by Finn10111** [comment]
@devyani08 Can you check your PYTHONPATH like this and check every directory if there is a dotenv directory?

    print(sys.path)

I think I just solved my issue: I installed python-dotenv within a virtual environment and tried to run my application with uvicorn web server (which was not installed with pip but globally using my package manager). Removing uvicorn and installing it with pip in the same virtual environment fixed it.

**Comment by devyani08** [comment]
> @devyani08 Can you check your PYTHONPATH like this and check every directory if there is a dotenv directory?
> 
> ```
> print(sys.path)
> ```
> 
> I think I just solved my issue: I installed python-dotenv within a virtual environment and tried to run my application with uvicorn web server (which was not installed with pip but globally using my package manager). Removing uvicorn and installing it with pip in the same virtual environment fixed it.

Certainly! Here's the revised sentence with the addition of "and it's working":

Thank you @Finn10111 for sharing the information. I cloned the repo using `git clone https://github.com/Torantulino/Auto-GPT.git` and successfully set up Auto-GPT, and it's currently functioning as expected.
