### ISSUE TITLE
.env not found in docker

### ISSUE THREAD

**Issue by Brice-D** [theskumar/python-dotenv#471]
Hello, 

project structure:

root_directory
  | --recommencer
        |-- src
             |-- services
                   __init__.py
                   extract.py (which is calling config = dotenv_values('../.env') -> it works locally)
          __init__.py
    app.py
.env (is in the root_directory)

While building my docker image and start my container (I've the same structure in my docker image/container as locally), extract.py can't find .env anymore, I have to call it like this **config = dotenv_values('.env')**. 
This make local testing difficult as I've to change how I call **config = dotenv_values()** while peforming my local test and change it to build my image. 

Any idea how I can solve this without changing my project structure?
![image](https://github.com/theskumar/python-dotenv/assets/24481556/26e50be0-1210-4718-af73-c7f5c5c678b1)

**Comment by fozziethebeat** [comment]
I recently started seeing the same problem.  I've given up on debugging it and decided to manually fix it by doing something like:

```python
config = dotenv_values('.env')
if os.environ.get("IMPORTANT_ENV") == None:
    os.environ["IMPORTANT_ENV"] = config.get("IMPORTANT_ENV")
```

**Comment by Brice-D** [comment]
I did the same, 

```
flask_debug = os.environ.get('FLASK_DEBUG')
config = any

if flask_debug is not None:
    config = dotenv_values('.env')
else:
    config = dotenv_values('../.env') # for local testing
```
