### ISSUE TITLE
dotenv module not found in python 3.11 version

### ISSUE THREAD

**Issue by BhuwanPandey** [theskumar/python-dotenv#488]
in main.py

from pathlib import Path
from dotenv import load_dotenv

env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)

Installed Packages
   python-dotenv     1.0.0

Operating System
     Ubuntu 22.04.2 LTS

Hy, there
Firstly, I install python-dotenv on virualenviroment  setup  with python version 3.11.0
I tried various methods of installing and uninstalling  by doing
-->  pip3 install python-dotenv
-->  python -m pip install python-dotenv
-->  pip3 install -U python-dotenv
-->  pip install -U python-dotenv

it's doesnot work then , i switch to python version 3.10.0 and it's then work

**Comment by theskumar** [comment]
@BhuwanPandey Feels like you probably installed python-dotenv while a different virtualenv was activated. Can you share the all the commands you ran to create and activate the virtualenv and the install this library. Also, version of python in that virtualenv. Thanks.

**Comment by BhuwanPandey** [comment]
I don't know how but its working  now..
