### ISSUE TITLE
missing cli option to run a given commandline

### ISSUE THREAD

**Issue by sloev** [theskumar/python-dotenv#49]
I think it would be neat if the `dotenv` cli tool had an option to run a given commandline WITH the environment vars sourced from specified file, like a RUNNER.

```
# using the env command to print out env
echo "foo=bar" > .env
$ dotenv -f .env env 
foo=bar
```

**Comment by sloev** [comment]
https://github.com/theskumar/python-dotenv/pull/50

**Comment by RckMrkr** [comment]
Would fit my workflow perfectly.

**Comment by sloev** [comment]
any news?

**Comment by venthur** [comment]
Thanks for implementing this feature. I actually think the "execute command using `.env` variables" should be the **default** action when no option is given. I.e. `dotenv some-command` should parse the `.env` file and run `some-command`. This is also the behaviour of `ruby-dotenv`'s `dotenv` command.
