### ISSUE TITLE
Truncates last character if .env file doesn't contain a trailing newline

### ISSUE THREAD

**Issue by nboley** [theskumar/python-dotenv#51]
If I have file.env:
```TEST=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ```
then the J is truncated from the key TEST
The following file gives the expected result:
```TEST=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ\n```

**Comment by theskumar** [comment]
@nboley thanks for reporting this. Will try to reproduce and fix this.

**Comment by theskumar** [comment]
Hi @nboley can you send me details of OS and other steps to reproduce this. Here is what i did.

![mar-30-2017 07-23-17](https://cloud.githubusercontent.com/assets/236356/24484078/ead13114-1519-11e7-97c9-f9514a5879b7.gif)

This command used is:

```
python -c "import os; from dotenv import load_dotenv; load_dotenv('.env'); print(os.environ['TEST'])"
```

**Comment by nboley** [comment]
Hi @theskumar,  

I was using the other (much worse) dotenv project. Really sorry for the bother, and thank you for taking a look.

Best, Nathan
