### ISSUE TITLE
Package ignores the first environment variable in a file

### ISSUE THREAD

**Issue by dablenparty** [theskumar/python-dotenv#526]
Hi, I have a fairly straightforward issue. When loading environment variables with `load_dotenv()`, it loads all variables except the first one. For example, my initial `.env` only had one value:
```
POSTGRESQL_PASSWORD=notarealpassword
```
After repeatedly getting `None` from `os.getenv("POSTGRESQL_PASSWORD")`, I changed my config to the following:
```
PLACEHOLDER=hi
POSTGRESQL_PASSWORD=notarealpassword
```
Now, `POSTGRESQL_PASSWORD` is defined, but `PLACEHOLDER` is `None`. If the two are swapped:
```
POSTGRESQL_PASSWORD=notarealpassword
PLACEHOLDER=hi
```
`POSTGRESQL_PASSWORD` becomes `None` again while `PLACEHOLDER` becomes `"hi"`. I have already tried using an absolute path to the `.env`, using the `override=True` parameter, and using `find_dotenv()` but nothing gets the library to parse the first variable. I'm on Windows 11 using Python 3.12.4 (installed with `pyenv`)

**Comment by Bajron** [comment]
Just guessing here, is you env-file perhaps encoded as UTF-8 with BOM?
I think it could result in such behavior.
Try installing cli variant (`pip install python-dotenv[cli]`) and then running `dotenv -f <your file> list`, is the variable there?

**Comment by dablenparty** [comment]
The `.env` is as follows:
```
PLACEHOLDER=hi
POSTGRESQL_PASSWORD=notarealpassword
```

Running `dotenv -f .env list` produces the following output

```
POSTGRESQL_PASSWORD=notarealpassword
ï»¿PLACEHOLDER=hi
```

Reformatting the output to `json` shows the erroneous bytes:

```
dotenv -f .env list --format json
{
  "POSTGRESQL_PASSWORD": "notarealpassword",
  "\u00ef\u00bb\u00bfPLACEHOLDER": "hi"
}
```

**Comment by Bajron** [comment]
So it is indeed BOM, see https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8 for details. Note the bytes in your output matches the byte sequence `EF BB BF`.

If you are calling `load_dotenv` and similar by yourself you can pass the argument `encoding="utf-8-sig"`. This makes the reader expect BOM in the file. By default the encoding is set to `"utf-8"`.

A workaround would be to leave the first line empty or put a comment there.

If you do not care about the BOM, I think it is [not recommended for UTF-8](https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-with-bom), you can choose different encoding in your editor.

In Notepad++ it would be in these places:
![image](https://github.com/user-attachments/assets/ce926a29-af08-4d48-9951-d386bee105f9)

In VS Code left click here
![image](https://github.com/user-attachments/assets/f1a468a2-4ef9-4416-9408-601a9837930c)
and then "Save with Encoding" and choose "UTF-8"

You can also rewrite the file in python like this:
```
with open(".env", "r", encoding="utf-8-sig") as src:
    content = src.read()

with open(".env", "w", encoding="utf-8") as dst:
    dst.write(content)
```

**Comment by dablenparty** [comment]
Thank you for the help! I'll just remove the BOM from my files.
