### ISSUE TITLE
Why does this module not load when executing cron

### ISSUE THREAD

**Issue by samaybhavsar** [theskumar/python-dotenv#54]

**Comment by leocavalcante** [comment]
Got the same using JavaScript's version. Maybe something related to cron's execution environment.

**Comment by foobar8675** [comment]
i was having the same issue on one of my aws linux instances. i changed my cron to this `* * * * * source $HOME/.bashrc cd /home/ec2-user/etl/ds_etl_service && /home/ec2-user/etl/ds_etl_service/run.sh` such that it uses the bash shell and can read the env vars.

**Comment by theskumar** [comment]
@samaybhavsar can you add more details as to how you are executing the cron command. Whether you are using the cli or using the dotenv instead a python script?
