### ISSUE TITLE
How to escape double quoted value?

### ISSUE THREAD

**Issue by rohitkrishna094** [theskumar/python-dotenv#542]
Assume my password is `hello"world` and the below is how I stored in `.env` file.

```
password="hello\"world"
```

Now I have a python script like so

```python
password= os.getenv("password")
print(password)
```

This prints `hello\"world`. Meaning it takes the literal backslash and still keeps it in the string. How to avoid it?

**Comment by Error7865** [comment]
Hey, Rohit
If you still facing this problem and your `password` was one line then you can do this:
```
password = hello"world
```
It will run correctly.

**Comment by rohitkrishna094** [comment]
Thanks it worked now. I also used this which seems to be working fine(however there is a warning saying it cannot parse, but it actually parses correctly)

`
password = "hello"world"
`
