### ISSUE TITLE
Add a `--version` CLI option as per the POSIX standard

### ISSUE THREAD

**Issue by kabirbaidhya** [theskumar/python-dotenv#56]
Almost all the CLI tools in the linux/unix world do follow the [POSIX standard](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html) for the CLI args & options. 
And the options like `--version` to print the version and `--help` to print out usage/help information are two of the most common options almost every CLI tool has. 

I think the `dotenv` tool needs this `--version` option too. 
Something like this:
```bash
$ dotenv --version
dotenv v0.6.4
```
Can do a PR for this if needed. 

Thanks.

**Comment by theskumar** [comment]
+1, please do :)
