### ISSUE TITLE
ImportError: cannot import name load_dotenv

### ISSUE THREAD

**Issue by sirvon** [theskumar/python-dotenv#6]
I've been getting this error on a python 2.7 installation:

```python
ImportError: cannot import name load_dotenv
```

any word on what gives?

**Comment by aniketmaithani** [comment]
@sirvon well make sure you have activated your `virtualenv` if you are using this inside it.

**Comment by theskumar** [comment]
@sirvon Please re-open this issue if the above solution doesn't work for you. Make sure, you have installed python dotenv and/or activated virtualenv.

**Comment by cnicodeme** [comment]
The issue is still present even in Debian Jessie. Please re-open it.

**Comment by cnicodeme** [comment]
Ok for future peoples that get here, the `load_dotenv` has been removed.

Do this instead :

```
import os
from dotenv import Dotenv
dotenv = Dotenv(os.path.join(os.path.dirname(__file__), ".env")) # Of course, replace by your correct path
os.environ.update(dotenv)
```

**Comment by saurabh-fueled** [comment]
@cnicodeme that's kind of strange as `Dotenv` was never part of this library. Are you sure, the library that you are using is python-dotenv and not something else. 

It would really helpful if you can post the output of your `pip freeze` command and/or 

```
import dotenv
print dir(dotenv)
```

Thanks,

**Comment by cnicodeme** [comment]
Yes of course,

But I'm also suspecting it's not the same "dotenv"? I installed it using `pip install dotenv`.

Here's the `print dir(dotenv)` result : 
`['Dotenv', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'get_variable', 'get_variables', 'set_variable', 'with_statement']`

And the `pip freeze` for dotenv :
`dotenv==0.0.5`

**Comment by saurabh-fueled** [comment]
@cnicodeme the correct install command is: 

```
pip install python-dotenv
```

You can simply fix this by
```
pip uninstall dotenv
pip install python-dotenv
```

Let me know if that helps!

Cheers!

**Comment by cnicodeme** [comment]
Thank you.

I already fixed my issue by doing what I indicated before (my second comment).

Cheers :)

**Comment by saurabh-fueled** [comment]
![](http://reactiongifs.me/wp-content/uploads/2013/10/i-wingman-successfully-leonardo-dicaprio.gif)

**Comment by sirvon** [comment]
why isnt this working on mac os el cap....
i forgot how i got this to work...

```bash
    from dotenv import load_dotenv
ImportError: cannot import name 'load_dotenv'
```

**Comment by waltertschwe** [comment]
I think this has changed again... has changed from "load_dotenv" to "load"
 so you would need to do this : 
```
dotenv_path = join(dirname(__file__), '.env')
load(dotenv_path)
```

**Comment by theskumar** [comment]
hi @waltertschwe, it has always been the same. 

I would suggest you run the following and see what's the output:

```
import dotenv
print dir(dotenv)
```

there is a high chance of library mismatch.

**Comment by MohamedAlaa** [comment]
Hi @theskumar 

I'm getting this error whenever i try to import dotenv:

```>>> import dotenv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/dotenv/__init__.py", line 1, in <module>
    from .cli import get_cli_string
  File "/usr/local/lib/python2.7/site-packages/dotenv/cli.py", line 3, in <module>
    import click
ImportError: No module named click```

**Comment by shlinx** [comment]
After uninstall dotenv, for my case it still didn't work. However, it works after I reinstall python-dotenv.
```
pip uninstall dotenv
pip uninstall python-dotenv
pip install python-dotenv
```

**Comment by jmrr** [comment]
@shlinx solution of uninstalling `dotenv` and `python-dotenv` and then reinstalling `python-dotenv` works. 

However, tools like `pipreqs` recognise the package as `dotenv` if not installed, and `python_dotenv` AND `dotenv` if installed. `pip freeze` discovers the dependency as `python-dotenv`.

What can be the long term solution?

**Comment by shaunakmukherjee** [comment]
Hey, I'm having a similar issue on an Ubuntu 16.04. The `pip freeze` command didn't help, and there's still an error saying that it can't import the 'load_dotenv'. Any ideas?
@theskumar could you give an insight?

**Comment by theskumar** [comment]
@shaunakmukherjee try uninstalling and installing `pip install python-dotenv`.

Best option would be to create and try inside a virtualenv.

**Comment by shaunakmukherjee** [comment]
@theskumar have already done them, as the picture shows. 

![load_dotenv](https://cloud.githubusercontent.com/assets/22137960/24987617/f37d637c-1fce-11e7-85aa-77f8af444290.PNG)

**Comment by theskumar** [comment]
Try in the `python manage.py shell`.

```
import dotenv
dir(dotenv)
```
what do you see?

**Comment by shaunakmukherjee** [comment]
`['Dotenv', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'get_variable', 'get_variables', 'set_variable', 'with_statement']
`

**Comment by theskumar** [comment]
@shaunakmukherjee you have dotenv installed which is not `python-dotenv` you need to uninstall it first. see: https://github.com/theskumar/python-dotenv/issues/6#issuecomment-266681747

**Comment by shaunakmukherjee** [comment]
Well, I have python-dotenv installed as well. 'pip freeze' shows a version of 'python-dotenv'.
@theskumar

**Comment by theist** [comment]
> Well, I have python-dotenv installed as well. 

@shaunakmukherjee  It seems that having python-dotenv *and* dotenv packages causes issues... I had the two installed and run into the same issue. I fixed it uninstalling dotenv and levaing python-dotenv instaled

**Comment by ltfschoen** [comment]
@theist When I run `pip install python-dotenv` it installs both **dotenv** and **python_dotenv** dependencies in the following directories:

/Users/<username>/miniconda3/lib/python3.6/site-packages/dotenv/
/Users/<username>/miniconda3/lib/python3.6/site-packages/python_dotenv-0.6.4.dist-info/

**Comment by djdeo** [comment]
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    dotenv.read_dotenv()
AttributeError: module 'dotenv' has no attribute 'read_dotenv'

after `pip install python_dotenv`

**Comment by theskumar** [comment]
@djdeo `read_dotenv()` is not part of this library, make sure you have installed the correct requirement, there are other dotenv python libraries as well.

**Comment by djdeo** [comment]
@theskumar  thanks, I tried `pip install django_dotenv` and it worked

**Comment by lexsoul** [comment]
`sudo apt install python3-dotenv`
worked for me in a Hyper-V virtual machine with Ubuntu 18.04

**Comment by tumispro** [comment]
@ltfschoen thanks, couldn't get the other package to work on MacOS Mojave either, that one worked perfectly!

**Comment by Prajwalprakash3722** [comment]
Uninstall dotenv and python-dotenv `sudo pip uninstall dotenv && sudo pip uninstall python-dotenv`
then install the python-dotenv `sudo pip install python-dotenv`

This really works

**Comment by felipeabou** [comment]
This is still happening. It's so annoying. No solution yet?

**Comment by RT-Tap** [comment]
I'm having this issue as well ... never installed dotenv only python-dotenv ... Getting `ImportError: cannot import name 'Dotenv' from partially initialized module 'dotenv' (most likely due to a circular import) (C:\Users\me\source\python\myapp\dotenv.py)` 
Tried `from dotenv import load_dotenv` and `from dotenv import Dotenv` as well as any other solutions I could find on stackoverflow and in this thread

**Comment by atheeralattar** [comment]
@RT-Tap Change your .py file name
