### ISSUE TITLE
click support can be optionall

### ISSUE THREAD

**Issue by hellysmile** [theskumar/python-dotenv#66]
There is no reason to force users to install http://click.pocoo.org/5/ .

**Comment by hartym** [comment]
Maybe dotenv could only install click in an extra? Like [cli] extra, so that depending on dotenv in another package would not install click as a collateral?

**Comment by theskumar** [comment]
Yeah. Having extra [cli] parameter to install sound like a plan. I'm going to priorities this for the next release. :)
