### ISSUE TITLE
Have load_dotenv return dictionary

### ISSUE THREAD

**Issue by ocervell** [theskumar/python-dotenv#68]
I really like that python-dotenv expands the variables based on what is in the dotenv file.
I would like to retrieve those expanded vars.

It would be nice if we could do something like:
```
# .env
DIR=/home/centos/myapp
LOGS_DIR={DIR}/logs
```

```
from dotenv import load_dotenv, find_dotenv
my_env = load_dotenv(find_dotenv())
print my_env['LOGS_DIR']
"/home/centos/myapp/logs"
```

Of course I could call it like:
```
import os
print os.environ['LOGS_DIR']
```

but I would need to know exactly the environment variable names defined in the env file.

**Comment by sanfilippopablo** [comment]
If you're looking for a quick workaround, just copy the code:
https://github.com/theskumar/python-dotenv/blob/05d123b8306d1e33311605f3d25bae0c51a47bc5/dotenv/main.py#L98-L115

**Comment by theskumar** [comment]
Returning of parsed values as dict is not officially exposed as public API. The internal function you are looking for to use is `dotenv_values`. (`from dotenv.main import dotenv_values`) and is not advised to use as it might change in future. 

```
from dotenv.main import dotenv_values
dict = dotenv_values('path_to_dotfile')
```

In future releases, I think we can expose this as public api with a proper name and documentation which be officially supported.

**Comment by ocervell** [comment]
In the meantime, can we add this in the README file, under a section named "Get environment as JSON" or something similar ? 

I'm sure many people will look for this, especially in the context of a web app where you need to have your environment as an object / dict.

**Comment by theskumar** [comment]
The docs are updated.
