### ISSUE TITLE
find_dotenv not working in nested directory

### ISSUE THREAD

**Issue by pthieu** [theskumar/python-dotenv#76]
I have a `.py` file in this directory heirarchy:

`$ROOT/module/service/service.py`

within my `service.py`, I have the following:

```
load_dotenv(find_dotenv())

DB_HOST = os.environ.get('DB_HOST', 'localhost')
DB_PORT = os.environ.get('DB_PORT', 27017)
DB_USERNAME = os.environ.get('DB_USERNAME', None)
DB_PASSWORD = os.environ.get('DB_PASSWORD', None)

print(f'DB Host: {DB_HOST}')
print(f'DB Port: {DB_PORT}')
print(f'DB Username: {DB_USERNAME}')
print(f'DB Password: {DB_PASSWORD}')
```

This prints:
```
DB Host: localhost
DB Port: 27017
DB Username: None
DB Password: None
```

If I instead change the first line to:
```
dotenv_path = os.path.join(os.path.dirname(__file__), '..', '..', '.env')
load_dotenv(dotenv_path)
```

It works and the printout is as expected. Is this expected behaviour? I figured the `find_dotenv()` will traverse to the root directory.

**Comment by sloria** [comment]
@pthieu Can you try using the latest version (0.9.1 as of this writing)?

**Comment by bbc2** [comment]
I can confirm it works now so I'm going to close this issue.

For your information, `load_dotenv()` is now equivalent to `load_dotenv(find_dotenv())`.
