### ISSUE TITLE
Multiline value not working as expected, better doc example needed

### ISSUE THREAD

**Issue by itaditya** [theskumar/python-dotenv#82]
I have this .env file

```
CLOUDKARAFKA_CA="-----BEGIN CERTIFICATE-----
MIIDAzCCAeugAwIBAgIJAL7UBqvWBRglMA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNV
someMoreLines
+HPBLZVg3o4jtzOJJNnaGCAcAHsm6PkqBhTUhM113r8MWlsR6eAIhIVtdRAxmjaw
6f7ARs8C8A==
-----END CERTIFICATE-----
"
CLOUDKARAFKA_CERT="-----BEGIN CERTIFICATE-----
MIICpzCCAY8CCQCA4JIEmpl1oTANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDDA12
someMoreLines
SSgZPE8qiN/jucTdLSLRQ0igohq4EnAg8QHXReX2oIlSZb7i8wxCqK/T+9WU0+vB
ToJ+bM0OCJ4d22I=
-----END CERTIFICATE-----
"
CLOUDKARAFKA_TOPIC_PREFIX="aj9g740d-"
CLOUDKARAFKA_BROKERS="velomobile-02.srvs.cloudkafka.com:9094,velomobile-01.srvs.cloudkafka.com:9094,velomobile-03.srvs.cloudkafka.com:9094"

```

When I use this .env file, the CLOUDKARAFKA_CA and CLOUDKARAFKA_CERT key are both "-----BEGIN CERTIFICATE-----"

![image](https://user-images.githubusercontent.com/15871340/34866042-19812a54-f7a1-11e7-9fef-c1178b5c479c.png)

Notice the extra `"`, Am I doing something wrong, please help

**Comment by itaditya** [comment]
python 3.6.4
python-dotenv 0.7.1

**Comment by theskumar** [comment]
@itaditya Have a look at https://github.com/theskumar/python-dotenv/issues/26

**Comment by itaditya** [comment]
I saw that you have solved the bug, but it's still not working in mine.

**Comment by iameugenejo** [comment]
your .env file should look like this:
 
`CLOUDKARAFKA_CA="-----BEGIN CERTIFICATE-----\nMIIDAzCCAeugAwIBAgIJAL7UBqvWBRglMA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNV\nsomeMoreLines\n+HPBLZVg3o4jtzOJJNnaGCAcAHsm6PkqBhTUhM113r8MWlsR6eAIhIVtdRAxmjaw\n6f7ARs8C8A==\n-----END CERTIFICATE-----\n"
CLOUDKARAFKA_CERT="-----BEGIN CERTIFICATE-----\nMIICpzCCAY8CCQCA4JIEmpl1oTANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDDA12\nsomeMoreLines\nSSgZPE8qiN/jucTdLSLRQ0igohq4EnAg8QHXReX2oIlSZb7i8wxCqK/T+9WU0+vB\nToJ+bM0OCJ4d22I=\n-----END CERTIFICATE-----\n"
CLOUDKARAFKA_TOPIC_PREFIX="aj9g740d-"
CLOUDKARAFKA_BROKERS="velomobile-02.srvs.cloudkafka.com:9094,velomobile-01.srvs.cloudkafka.com:9094,velomobile-03.srvs.cloudkafka.com:9094"`

PR #32 would make your .env to work as is.

**Comment by itaditya** [comment]
This looks a little counterintuitive, why should I add newline characters. Anyways I switched to another solution.

**Comment by iameugenejo** [comment]
I believe `\n` has been used as a mean to break lines in a string variable since the beginning of programming languages.

It would be counterintuitive if you use languages or scripts that has multiline string literal feature.

And I guess you are more familiar with those that support it.

**Comment by itaditya** [comment]
No I didn't mean it like that. I'm saying that the .env feature enabling utils named dotenv available, like node dotenv (https://www.npmjs.com/package/dotenv) and heroku env files don't need the \n. A developer like me coming from these areas would naturally think that if a module is named python-**dotenv** would work exactly the same. I hope you understand my point.

**Comment by itaditya** [comment]
Also I noticed you explicitly mention that this util enables functionality just like heroku. And heroku doesn't complain if I don't use `\n`. :wink:

**Comment by itaditya** [comment]
Also if anyone else is interested I used this utility later https://github.com/kpachnis/python-dotenv

**Comment by iameugenejo** [comment]
Well I don't think I mentioned anything about heroku. What my PR did was to allow this module to parse quoted value, and that also allowed multiline string value to be used as it allowed control characters such as `\n`.

You, or even the author of the other python-dotenv, could've forked this repo, make improvement that's needed and sent PR to this. And I believe that's how Open Source community works. (That is unless the maintainer doesn't maintain the repo anymore or refuses to accept valid PRs)

I'm glad that you found another solution that works, and hope this repo's maintainer merges the other PR I mentioned that solves your issue.

**Comment by itaditya** [comment]
I'm not complaining about your PR, I don't know anything about it. I'm just a user of this utility and I found one flaw so I pointed it out. At that time I needed a quick solution, the `\n` thing was not mentioned anywhere, so I waited for a reply. It's great that you eventually replied but I was forced to look for another solution. I agree with you that I should also contribute to this project by making PRs but I think that is not the only way. The first step must be to open issues and find out if the problem is worth working on, and that I did. I understand that you are defending your work and that's fine (we're humans).  After I opened the issue @theskumar promptly replied that I should check #26 , that meant that the utility is fine and I'm doing something wrong, so there is no sense in making PRs. Now as you have mentioned that we have to use `\n`, I and others who will be reading this, will have a working fix for their problems, so in a way we together have contributed to this project. And I think that's just the way OSS works. 
PS - The heroku thing is mentioned in the description just below the title of the repo.
![image](https://user-images.githubusercontent.com/15871340/35372509-5f12682a-01c0-11e8-9dc6-4fc1766d87a9.png)

**Comment by iameugenejo** [comment]
Why do you think I'm defending my PR when I'm even suggesting the other PR should be merged, which in turn would replace the changes my PR made.

Great that you realized that this repo lacks documentation about the feature. Why not make your contribution worth more by sending a PR for the improvement to README.md?

**Comment by itaditya** [comment]
Cool then, I'll make one then

**Comment by itaditya** [comment]
Check out my PR #85

**Comment by theskumar** [comment]
@itaditya thanks for the docs, I think it can utilize some more explanation, like the values would need to be quoted. I'm going to merge that none-the-less. :-)

I believe documentation overall can be better organized now (into multiple pages maybe) as there are lot of functionality and edge cases. I'll get to that when I get some free time.

**Comment by theskumar** [comment]
I'm closing this issue, a multi-line value should use the `\n` newline delimiter and python-dotenv will correctly put that in the system environment variable. 

@itaditya the way you have set the value won't be supported. Please use the `\n` to indicate newlines.

**Comment by chaoflow** [comment]
@theskumar What is the rationale not to support newline characters in quoted strings?

**Comment by amancevice** [comment]
I have opened #142 to fix this issue. The changes I'm proposing don't break any existing tests and address @itaditya's use case.

I know this issue has been closed, but I think it's important to support implicit (as opposed to manually adding `\n` chars) newlines in `.env` files so that it more closely matches the behavior of other languages, not to mention a simple `source .env`

**Comment by alekcastillo-sdc** [comment]
So, no multiline vars yet?

**Comment by stephan9mertel** [comment]
Hi, I just ran into the same issue. Multi-line variables don't work for me, neither with nor without the `\n` at the end of each line. Any updates on this?

**Comment by bbc2** [comment]
This is a very old issue and the discussion here is irrelevant given how much python-dotenv has changed since it took place.   Multiline variables are supposed to work now.  If that's not the case for you, could you create a new issue with a minimal example and the versions of Python and python-dotenv that you use?

**Comment by stephan9mertel** [comment]
Thanks for your fast reply @bbc2 ! I created this issue: https://github.com/theskumar/python-dotenv/issues/289

**Comment by DetachHead** [comment]
> I'm closing this issue, a multi-line value should use the `\n` newline delimiter and python-dotenv will correctly put that in the system environment variable.
> 
> @itaditya the way you have set the value won't be supported. Please use the `\n` to indicate newlines.

@theskumar then why does [the documentation](https://github.com/theskumar/python-dotenv#multiline-values) say that both methods are supported?
