### ISSUE TITLE
Boolean field

### ISSUE THREAD

**Issue by ArtikUA** [theskumar/python-dotenv#86]
Is that is possible to define boolean field in .env file using python-dotenv?

**Comment by theskumar** [comment]
Short answer is No. This library only support string. string are the only thing possible to be set as system environment variable. 

You can have your own logic or something like django-environ to read from environment variable and parse it to a valid data structure.

**Comment by attack68** [comment]
Since it reads strings is the simplest solution not:

    # .env .. for False set ""
    KEY_TRUE="1"
    KEY_FALSE=""

    # manage.py..
    assert Bool(os.getenv('KEY_TRUE')
    assert not Bool(os.getenv('KEY_FALSE')

**Comment by guettli** [comment]
You can use this small helper lib to parse a env var to boolean: https://pypi.org/project/env-flag/

**Comment by DaveParr** [comment]
A trivial workaround (/ abuse of a standard) is to use `quote_mode="never"`:
```
dotenv.set_key(env_file, "MY_COOL_BOOL", tracing, quote_mode="never")
```

Where `tracing` is either a value of `True` or `False`. This seems to work as intended by  projects like [LangSmith which look for a bool not a str in the environment](https://docs.smith.langchain.com/tracing/quick_start#:~:text=3.%20Configure%20your%20environment,openai%2Dapi%2Dkey%3E) to be set, but type checkers will be angry, and hypothetically this is 'Unintended Behaviour' so YMMV, use at your won risk etc.
