### ISSUE TITLE
`dotenv set` cannot accept values that start with `-`

### ISSUE THREAD

**Issue by kenmclennan** [theskumar/python-dotenv#87]
In trying to set an RSA key which starts with `-----BEGIN RSA PRIVATE KEY-----`, the command line helper `dotenv set` fails with the following:

```
Error: no such option: [my-secret-value]
```

That should be enough to recreate. Any thoughts?

**Comment by skeledrew** [comment]
I also have this problem. Is there a fix? Using version 0.8.2
