### ISSUE TITLE
python3 only?

### ISSUE THREAD

**Issue by reppolice** [theskumar/python-dotenv#90]
In Ubuntu, I get   RuntimeError: uvloop requires Python 3.5 or greater

But

python3 src/chess_zero/run.py self
Traceback (most recent call last):
  File "src/chess_zero/run.py", line 19, in <module>
    from chess_zero import manager
  File "src/chess_zero/manager.py", line 38
    logger.info(f"config type: {config_type}")
SyntaxError: invalid syntax

Is some typo lurking in the code?                                            ^

**Comment by theskumar** [comment]
@reppolice this doesn't seem be code from python-dotenv or directly related to python-dotenv. This library as of now is both python 2.7 and 3.

**Comment by reppolice** [comment]
OMG wrong tab! You are right!
