### ISSUE TITLE
Allow variables to be prefixed with "export"

### ISSUE THREAD

**Issue by nicholastmosher** [theskumar/python-dotenv#91]
Hi there. In Rust there's also a [dotenv library](https://crates.io/crates/dotenv#examples) which is very similar but has a nice additional feature:

> You can optionally prefix each line with the word export, which will conveniently allow you to source the whole file on your shell.

So a `.env` file essentially has extended syntax which makes the following valid:

```sh
export MY_API_KEY="blah"
```

This comes in handy because during local development because some command line developer tools need access to the same environment variables that your application does (e.g. if you want to use `curl` to test an API endpoint that your application uses).

**Comment by JonathanPorta** [comment]
@nicholastmosher There's a PR [here](https://github.com/theskumar/python-dotenv/pull/62) that handles the use case you have proposed.

**Comment by theskumar** [comment]
@nicholastmosher I don't really mine having this feature in, this would just need to be implemented properly. I've left comment in the PR by @slavaGanzin 

FYIW, the current structure of .env is exportable to shell quite easily with `set -a` flag before source command. See https://github.com/theskumar/python-dotenv/issues/20#issuecomment-189159436

**Comment by theskumar** [comment]
Support for this is available in 0.8.0 🎉
